// ── Types ──────────────────────────────────────────────────────────────────

export type MealType =
  | "petit-dej"
  | "dejeuner"
  | "diner"
  | "collation"
  | "post-training"
  | "dessert";

export type Diet = "omnivore" | "vegetarien" | "vegan" | "pescetarien";

export type Phase = "surplus" | "maintenance" | "deficit";

export type Season = "printemps" | "ete" | "automne" | "hiver" | "toute-saison";

export type Temp = "chaud" | "froid" | "tiede";

export type Allergen =
  | "gluten"
  | "lactose"
  | "oeuf"
  | "fruits-a-coque"
  | "poisson"
  | "crustaces"
  | "soja"
  | "arachide";

export interface Recipe {
  id: string;
  name: string;
  meal: MealType;
  diet: Diet[];
  phases: Phase[];
  season: Season[];
  temp: Temp;
  texture: string[];
  price: 1 | 2 | 3; // € / €€ / €€€
  region: string;
  prepMinutes: number;
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  allergens: Allergen[];
  ingredients: string[];
  steps: string[];
  tip: string;
  /** Recette signature réservée — débloquée par l'abonnement ou par rang (voir lib/gamification.ts). */
  exclusive?: boolean;
}

// ── Labels pour l'UI ──────────────────────────────────────────────────────

export const MEAL_LABELS: Record<MealType, string> = {
  "petit-dej": "Petit-déjeuner",
  dejeuner: "Déjeuner",
  diner: "Dîner",
  collation: "Collation",
  "post-training": "Post-training",
  dessert: "Dessert",
};

export const DIET_LABELS: Record<Diet, string> = {
  omnivore: "Omnivore",
  vegetarien: "Végétarien",
  vegan: "Vegan",
  pescetarien: "Pescétarien",
};

export const PHASE_LABELS: Record<Phase, string> = {
  surplus: "Surplus (prise de masse)",
  maintenance: "Maintenance",
  deficit: "Déficit (sèche)",
};

export const SEASON_LABELS: Record<Season, string> = {
  printemps: "Printemps",
  ete: "Été",
  automne: "Automne",
  hiver: "Hiver",
  "toute-saison": "Toute saison",
};

export const TEMP_LABELS: Record<Temp, string> = {
  chaud: "Chaud",
  froid: "Froid",
  tiede: "Tiède",
};

export const ALLERGEN_LABELS: Record<Allergen, string> = {
  gluten: "Gluten",
  lactose: "Lactose",
  oeuf: "Œuf",
  "fruits-a-coque": "Fruits à coque",
  poisson: "Poisson",
  crustaces: "Crustacés",
  soja: "Soja",
  arachide: "Arachide",
};

export const PRICE_LABELS: Record<1 | 2 | 3, string> = {
  1: "€",
  2: "€€",
  3: "€€€",
};

// ── Base de recettes ──────────────────────────────────────────────────────

export const RECIPES: Recipe[] = [
  // ─────────────────────────── PETIT-DÉJEUNER ───────────────────────────
  {
    id: "pdj-omelette-epinards",
    name: "Omelette aux épinards et comté",
    meal: "petit-dej",
    diet: ["omnivore", "vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant", "moelleux"],
    price: 1,
    region: "France entière",
    prepMinutes: 10,
    kcal: 380,
    protein: 32,
    carbs: 4,
    fat: 26,
    allergens: ["oeuf", "lactose"],
    ingredients: ["3 œufs", "Poignée d'épinards frais", "30g de comté râpé", "Sel, poivre, muscade"],
    steps: [
      "Faire tomber les épinards 2 min à la poêle",
      "Battre les œufs, ajouter le comté",
      "Verser sur les épinards, cuire 3-4 min à feu doux",
      "Plier en deux, servir immédiatement",
    ],
    tip: "Ajoute une tranche de pain de seigle grillé si tu es en surplus.",
  },
  {
    id: "pdj-porridge-fruits-rouges",
    name: "Porridge d'avoine, fruits rouges et amandes",
    meal: "petit-dej",
    diet: ["vegetarien", "vegan"],
    phases: ["surplus", "maintenance"],
    season: ["ete", "printemps"],
    temp: "chaud",
    texture: ["crémeux", "croquant"],
    price: 1,
    region: "France entière",
    prepMinutes: 8,
    kcal: 420,
    protein: 14,
    carbs: 58,
    fat: 14,
    allergens: ["fruits-a-coque"],
    ingredients: ["60g de flocons d'avoine", "250ml de lait (ou végétal)", "Fruits rouges (frais ou surgelés)", "1 c. à soupe d'amandes effilées", "Miel ou sirop d'érable"],
    steps: [
      "Cuire les flocons d'avoine dans le lait 5 min à feu doux",
      "Verser dans un bol, ajouter les fruits rouges",
      "Parsemer d'amandes effilées et d'un trait de miel",
    ],
    tip: "Remplace le lait par du lait végétal et le miel par du sirop d'agave pour une version 100% vegan.",
  },
  {
    id: "pdj-pancakes-proteines",
    name: "Pancakes protéinés banane-avoine",
    meal: "petit-dej",
    diet: ["vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["moelleux"],
    price: 1,
    region: "France entière",
    prepMinutes: 15,
    kcal: 510,
    protein: 36,
    carbs: 62,
    fat: 12,
    allergens: ["oeuf", "lactose"],
    ingredients: ["1 banane mûre", "2 œufs", "40g de flocons d'avoine mixés", "30g de whey vanille", "1/2 c. à café de levure", "Un peu de lait"],
    steps: [
      "Mixer tous les ingrédients pour obtenir une pâte lisse",
      "Cuire des petites portions à la poêle chaude, 2 min par face",
      "Servir avec fruits frais ou un peu de beurre de cacahuète",
    ],
    tip: "Excellent petit-déj pré ou post-séance grâce au ratio glucides/protéines.",
  },
  {
    id: "pdj-bol-skyr-granola",
    name: "Bol de skyr, granola maison et fruits de saison",
    meal: "petit-dej",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux", "croquant"],
    price: 2,
    region: "France entière",
    prepMinutes: 5,
    kcal: 320,
    protein: 30,
    carbs: 32,
    fat: 8,
    allergens: ["lactose", "fruits-a-coque"],
    ingredients: ["200g de skyr nature", "30g de granola pauvre en sucre", "Fruits de saison (pomme, poire, fruits rouges)", "Cannelle"],
    steps: [
      "Verser le skyr dans un bol",
      "Ajouter les fruits coupés et le granola",
      "Saupoudrer de cannelle",
    ],
    tip: "Le skyr a deux fois plus de protéines qu'un yaourt grec classique pour le même nombre de calories — parfait en sèche.",
  },
  {
    id: "pdj-toast-avocat-oeuf",
    name: "Toast avocat, œuf poché et graines",
    meal: "petit-dej",
    diet: ["vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["croquant", "fondant"],
    price: 2,
    region: "France entière",
    prepMinutes: 12,
    kcal: 440,
    protein: 20,
    carbs: 32,
    fat: 26,
    allergens: ["gluten", "oeuf"],
    ingredients: ["2 tranches de pain complet", "1/2 avocat", "1 œuf", "Graines de sésame/courge", "Citron, piment d'Espelette"],
    steps: [
      "Toaster le pain",
      "Écraser l'avocat avec citron et sel, étaler sur le pain",
      "Pocher l'œuf 3 min dans l'eau frémissante avec un peu de vinaigre",
      "Déposer l'œuf sur le toast, parsemer de graines et de piment",
    ],
    tip: "Version sans gluten facile : pain de sarrasin ou de riz.",
  },
  {
    id: "pdj-smoothie-bowl-mangue",
    name: "Smoothie bowl mangue-passion",
    meal: "petit-dej",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete"],
    temp: "froid",
    texture: ["crémeux", "croquant"],
    price: 2,
    region: "France entière (fruits exotiques importés)",
    prepMinutes: 10,
    kcal: 290,
    protein: 8,
    carbs: 52,
    fat: 6,
    allergens: ["fruits-a-coque"],
    ingredients: ["1 mangue congelée", "1 banane", "100ml de lait végétal", "1 fruit de la passion", "Noix de coco râpée, granola"],
    steps: [
      "Mixer mangue, banane et lait végétal jusqu'à texture épaisse",
      "Verser dans un bol",
      "Garnir de fruit de la passion, coco râpée et granola",
    ],
    tip: "Très rafraîchissant après une séance d'été — facile à digérer avant un entraînement aussi.",
  },
  {
    id: "pdj-pain-perdu-proteine",
    name: "Pain perdu protéiné cannelle",
    meal: "petit-dej",
    diet: ["vegetarien"],
    phases: ["surplus"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["moelleux", "fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 12,
    kcal: 480,
    protein: 28,
    carbs: 58,
    fat: 14,
    allergens: ["gluten", "oeuf", "lactose"],
    ingredients: ["2-3 tranches de pain rassis", "2 œufs", "20g de whey vanille diluée dans du lait", "Cannelle", "Un peu de beurre pour la cuisson"],
    steps: [
      "Mélanger œufs, lait protéiné et cannelle",
      "Tremper les tranches de pain 30 sec de chaque côté",
      "Cuire à la poêle beurrée 2-3 min par face",
      "Servir avec fruits ou sirop d'érable",
    ],
    tip: "Pain rassis = idéal, il absorbe mieux le mélange sans se déliter.",
  },

  // ─────────────────────────── DÉJEUNER ───────────────────────────
  {
    id: "dej-poulet-riz-brocoli",
    name: "Poulet grillé, riz basmati et brocoli vapeur",
    meal: "dejeuner",
    diet: ["omnivore"],
    phases: ["surplus", "maintenance", "deficit"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["moelleux", "croquant"],
    price: 2,
    region: "France entière",
    prepMinutes: 25,
    kcal: 520,
    protein: 48,
    carbs: 55,
    fat: 10,
    allergens: [],
    ingredients: ["180g de blanc de poulet", "80g de riz basmati (cru)", "200g de brocoli", "Huile d'olive, ail, paprika"],
    steps: [
      "Mariner le poulet avec ail, paprika et huile d'olive",
      "Cuire le riz selon les instructions",
      "Griller le poulet 6-7 min par face",
      "Cuire le brocoli à la vapeur 6 min, assaisonner",
    ],
    tip: "Le plat de référence en musculation — ajuste juste la quantité de riz selon ta phase.",
  },
  {
    id: "dej-buddha-bowl-pois-chiches",
    name: "Buddha bowl pois chiches rôtis et tahini",
    meal: "dejeuner",
    diet: ["vegan", "vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["toute-saison"],
    temp: "tiede",
    texture: ["croquant", "crémeux"],
    price: 2,
    region: "France entière (inspiration méditerranéenne)",
    prepMinutes: 30,
    kcal: 470,
    protein: 20,
    carbs: 58,
    fat: 18,
    allergens: ["soja"],
    ingredients: ["200g de pois chiches cuits", "Quinoa", "Carottes, chou rouge, concombre", "Sauce tahini-citron", "Graines de sésame"],
    steps: [
      "Rôtir les pois chiches au four 20 min avec cumin et paprika",
      "Cuire le quinoa",
      "Disposer tous les légumes crus et le quinoa dans un bol",
      "Arroser de sauce tahini-citron",
    ],
    tip: "Excellente source de protéines végétales complètes en combinant légumineuse + céréale.",
  },
  {
    id: "dej-saumon-patate-douce",
    name: "Pavé de saumon, purée de patate douce, épinards",
    meal: "dejeuner",
    diet: ["pescetarien", "omnivore"],
    phases: ["surplus", "maintenance"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["fondant", "crémeux"],
    price: 3,
    region: "Bretagne / Norvège (saumon)",
    prepMinutes: 25,
    kcal: 580,
    protein: 38,
    carbs: 48,
    fat: 24,
    allergens: ["poisson"],
    ingredients: ["150g de pavé de saumon", "250g de patate douce", "Épinards frais", "Huile d'olive, citron, aneth"],
    steps: [
      "Cuire la patate douce à l'eau, écraser en purée avec un peu d'huile d'olive",
      "Cuire le saumon à la poêle peau croustillante, 4 min par face",
      "Faire revenir les épinards 2 min",
      "Dresser et arroser de citron",
    ],
    tip: "Riche en oméga-3 — excellent pour la récupération articulaire des sportifs.",
  },
  {
    id: "dej-salade-lentilles-feta",
    name: "Salade de lentilles, feta et tomates confites",
    meal: "dejeuner",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete", "printemps"],
    temp: "froid",
    texture: ["fondant", "croquant"],
    price: 2,
    region: "Provence",
    prepMinutes: 20,
    kcal: 420,
    protein: 22,
    carbs: 40,
    fat: 18,
    allergens: ["lactose"],
    ingredients: ["200g de lentilles corail ou vertes cuites", "60g de feta", "Tomates cerises confites", "Roquette, huile d'olive, vinaigre balsamique"],
    steps: [
      "Mélanger les lentilles tiédies avec huile d'olive et vinaigre",
      "Ajouter la roquette et les tomates confites",
      "Émietter la feta sur le dessus",
    ],
    tip: "Parfaite en lunchbox, se prépare la veille et se mange froide ou tiède.",
  },
  {
    id: "dej-wrap-dinde-crudites",
    name: "Wrap de dinde, crudités et sauce yaourt",
    meal: "dejeuner",
    diet: ["omnivore"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["croquant"],
    price: 1,
    region: "France entière",
    prepMinutes: 10,
    kcal: 380,
    protein: 32,
    carbs: 38,
    fat: 10,
    allergens: ["gluten", "lactose"],
    ingredients: ["1 galette de blé complet", "120g de blanc de dinde", "Carotte, concombre, salade", "Yaourt grec, moutarde, citron"],
    steps: [
      "Mélanger yaourt, moutarde et citron pour la sauce",
      "Garnir la galette de crudités et de dinde",
      "Napper de sauce, rouler serré",
    ],
    tip: "Idéal pour un repas rapide au bureau — se prépare en moins de 10 minutes.",
  },
  {
    id: "dej-pates-completes-thon",
    name: "Pâtes complètes, thon, olives et tomates",
    meal: "dejeuner",
    diet: ["pescetarien"],
    phases: ["surplus", "maintenance"],
    season: ["ete"],
    temp: "tiede",
    texture: ["fondant"],
    price: 1,
    region: "Méditerranée / Sud de la France",
    prepMinutes: 18,
    kcal: 540,
    protein: 36,
    carbs: 65,
    fat: 14,
    allergens: ["gluten", "poisson"],
    ingredients: ["90g de pâtes complètes (crues)", "1 boîte de thon au naturel", "Tomates cerises, olives noires", "Huile d'olive, basilic, ail"],
    steps: [
      "Cuire les pâtes al dente",
      "Faire revenir l'ail et les tomates 5 min",
      "Ajouter le thon égoutté et les olives",
      "Mélanger avec les pâtes, basilic frais",
    ],
    tip: "Version sans gluten : utilise des pâtes de lentilles ou de riz.",
  },
  {
    id: "dej-curry-pois-chiches-vegan",
    name: "Curry de pois chiches et lait de coco",
    meal: "dejeuner",
    diet: ["vegan", "vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["crémeux"],
    price: 1,
    region: "France entière (inspiration indienne)",
    prepMinutes: 25,
    kcal: 480,
    protein: 16,
    carbs: 52,
    fat: 22,
    allergens: [],
    ingredients: ["240g de pois chiches cuits", "200ml de lait de coco", "Oignon, ail, gingembre", "Curry, curcuma, cumin", "Riz basmati"],
    steps: [
      "Faire revenir oignon, ail et gingembre",
      "Ajouter les épices puis le lait de coco",
      "Incorporer les pois chiches, mijoter 15 min",
      "Servir sur riz basmati",
    ],
    tip: "Se congèle très bien — fais une double dose pour la semaine.",
  },
  {
    id: "dej-steak-haricots-verts",
    name: "Steak de bœuf, haricots verts et riz",
    meal: "dejeuner",
    diet: ["omnivore"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant", "croquant"],
    price: 3,
    region: "Charolais / France entière",
    prepMinutes: 20,
    kcal: 560,
    protein: 45,
    carbs: 45,
    fat: 20,
    allergens: [],
    ingredients: ["180g de steak de bœuf", "200g de haricots verts", "70g de riz (cru)", "Beurre, ail, thym"],
    steps: [
      "Cuire le riz",
      "Cuire les haricots verts à la vapeur 8 min",
      "Saisir le steak 2-3 min par face avec beurre, ail et thym",
      "Laisser reposer 3 min avant de trancher",
    ],
    tip: "Pour la sèche, réduis simplement la portion de riz à 50g.",
  },
  {
    id: "dej-tofu-saute-legumes",
    name: "Tofu sauté, légumes croquants et sauce soja-gingembre",
    meal: "dejeuner",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["croquant", "fondant"],
    price: 1,
    region: "France entière (inspiration asiatique)",
    prepMinutes: 18,
    kcal: 380,
    protein: 24,
    carbs: 30,
    fat: 18,
    allergens: ["soja"],
    ingredients: ["200g de tofu ferme", "Poivrons, brocoli, carottes", "Sauce soja, gingembre, ail", "Huile de sésame"],
    steps: [
      "Presser et couper le tofu en dés, le saisir à la poêle jusqu'à coloration",
      "Réserver, faire sauter les légumes 5 min à feu vif",
      "Réunir tofu et légumes, ajouter sauce soja, gingembre et ail",
      "Finir avec un trait d'huile de sésame",
    ],
    tip: "Presser le tofu au moins 15 min avant cuisson pour une texture bien croustillante.",
  },
  {
    id: "dej-quiche-legere-courgette",
    name: "Quiche sans pâte courgette-chèvre",
    meal: "dejeuner",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete"],
    temp: "tiede",
    texture: ["fondant", "moelleux"],
    price: 2,
    region: "Provence",
    prepMinutes: 35,
    kcal: 350,
    protein: 24,
    carbs: 12,
    fat: 22,
    allergens: ["oeuf", "lactose"],
    ingredients: ["4 œufs", "200ml de lait", "1 courgette", "80g de chèvre frais", "Herbes de Provence"],
    steps: [
      "Couper la courgette en fines rondelles, les faire suer 5 min",
      "Battre œufs et lait, assaisonner",
      "Verser dans un plat avec la courgette et le chèvre émietté",
      "Cuire 25 min à 180°C",
    ],
    tip: "Sans pâte = beaucoup moins de glucides et de calories qu'une quiche classique, idéal en sèche.",
  },

  // ─────────────────────────── DÎNER ───────────────────────────
  {
    id: "din-cabillaud-legumes-four",
    name: "Cabillaud en papillote et légumes rôtis",
    meal: "diner",
    diet: ["pescetarien"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant"],
    price: 2,
    region: "Atlantique / France entière",
    prepMinutes: 30,
    kcal: 380,
    protein: 38,
    carbs: 22,
    fat: 14,
    allergens: ["poisson"],
    ingredients: ["180g de cabillaud", "Courgette, poivron, tomate", "Citron, thym, huile d'olive"],
    steps: [
      "Disposer le poisson et les légumes coupés sur du papier sulfurisé",
      "Arroser d'huile d'olive, citron et thym",
      "Fermer la papillote, cuire 20 min à 200°C",
    ],
    tip: "Plat très léger en calories mais rassasiant — parfait pour un dîner en phase de sèche.",
  },
  {
    id: "din-soupe-legumes-hiver",
    name: "Velouté de légumes d'hiver et croûtons",
    meal: "diner",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit"],
    season: ["hiver", "automne"],
    temp: "chaud",
    texture: ["crémeux", "croquant"],
    price: 1,
    region: "France entière",
    prepMinutes: 30,
    kcal: 220,
    protein: 6,
    carbs: 32,
    fat: 6,
    allergens: ["gluten"],
    ingredients: ["Carottes, potiron, poireaux", "Bouillon de légumes", "Pain grillé en croûtons", "Crème végétale (optionnel)"],
    steps: [
      "Faire revenir les légumes coupés 5 min",
      "Ajouter le bouillon, cuire 25 min",
      "Mixer jusqu'à texture lisse",
      "Servir avec croûtons et un trait de crème végétale",
    ],
    tip: "Très faible en calories pour le volume — excellent dîner en déficit qui cale bien.",
  },
  {
    id: "din-omelette-jambon-salade",
    name: "Omelette jambon blanc et salade verte",
    meal: "diner",
    diet: ["omnivore"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 10,
    kcal: 340,
    protein: 30,
    carbs: 4,
    fat: 22,
    allergens: ["oeuf"],
    ingredients: ["3 œufs", "1 tranche de jambon blanc", "Salade verte", "Vinaigrette légère"],
    steps: [
      "Battre les œufs, ajouter le jambon coupé en dés",
      "Cuire à la poêle 3-4 min",
      "Servir avec une salade verte assaisonnée",
    ],
    tip: "Le dîner classique 'sans prise de tête' pour rester dans ses macros sans calculer.",
  },
  {
    id: "din-poke-bowl-saumon",
    name: "Poke bowl saumon, riz vinaigré et edamame",
    meal: "diner",
    diet: ["pescetarien"],
    phases: ["maintenance", "surplus"],
    season: ["ete"],
    temp: "froid",
    texture: ["fondant", "croquant"],
    price: 3,
    region: "France entière (inspiration hawaïenne)",
    prepMinutes: 20,
    kcal: 520,
    protein: 34,
    carbs: 55,
    fat: 16,
    allergens: ["poisson", "soja"],
    ingredients: ["150g de saumon frais (qualité sashimi)", "Riz vinaigré", "Edamame, avocat, concombre", "Sauce soja, sésame"],
    steps: [
      "Cuire le riz, l'assaisonner avec vinaigre de riz et sucre",
      "Couper le saumon en cubes",
      "Disposer riz, saumon, edamame, avocat et concombre dans un bol",
      "Arroser de sauce soja et graines de sésame",
    ],
    tip: "Achète un saumon labellisé 'qualité sashimi' chez le poissonnier si tu le manges cru.",
  },
  {
    id: "din-ratatouille-oeuf",
    name: "Ratatouille provençale et œuf au plat",
    meal: "diner",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete"],
    temp: "chaud",
    texture: ["fondant"],
    price: 1,
    region: "Provence",
    prepMinutes: 35,
    kcal: 320,
    protein: 16,
    carbs: 22,
    fat: 18,
    allergens: ["oeuf"],
    ingredients: ["Courgette, aubergine, poivron, tomate", "Ail, oignon, herbes de Provence", "2 œufs", "Huile d'olive"],
    steps: [
      "Couper tous les légumes en dés",
      "Faire mijoter 30 min avec ail, oignon et herbes",
      "Cuire les œufs au plat",
      "Servir la ratatouille surmontée des œufs",
    ],
    tip: "Recette estivale typique du sud de la France, se prépare en grande quantité et se réchauffe toute la semaine.",
  },
  {
    id: "din-galette-sarrasin-jambon",
    name: "Galette de sarrasin jambon-œuf-fromage (complète bretonne)",
    meal: "diner",
    diet: ["omnivore"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant", "croquant"],
    price: 2,
    region: "Bretagne",
    prepMinutes: 20,
    kcal: 480,
    protein: 32,
    carbs: 38,
    fat: 22,
    allergens: ["oeuf", "lactose"],
    ingredients: ["1 galette de sarrasin", "1 tranche de jambon", "1 œuf", "Emmental râpé"],
    steps: [
      "Chauffer la galette dans une poêle",
      "Casser l'œuf au centre, ajouter jambon et fromage",
      "Replier les bords en carré, cuire jusqu'à ce que le blanc soit pris",
    ],
    tip: "Le sarrasin est naturellement sans gluten — vérifie juste que la galette est pure sarrasin si allergie.",
  },
  {
    id: "din-dahl-lentilles-corail",
    name: "Dahl de lentilles corail au lait de coco",
    meal: "diner",
    diet: ["vegan", "vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["crémeux"],
    price: 1,
    region: "France entière (inspiration indienne)",
    prepMinutes: 30,
    kcal: 400,
    protein: 18,
    carbs: 48,
    fat: 14,
    allergens: [],
    ingredients: ["200g de lentilles corail", "150ml de lait de coco", "Curcuma, cumin, coriandre", "Oignon, ail, tomate"],
    steps: [
      "Faire revenir oignon et ail, ajouter les épices",
      "Ajouter lentilles, tomate et eau, cuire 20 min",
      "Incorporer le lait de coco en fin de cuisson",
      "Servir avec coriandre fraîche",
    ],
    tip: "Plat réconfortant et économique, riche en fibres pour la satiété en phase de sèche.",
  },
  {
    id: "din-tartare-boeuf-frites-patate",
    name: "Tartare de bœuf maison et frites de patate douce au four",
    meal: "diner",
    diet: ["omnivore"],
    phases: ["surplus"],
    season: ["toute-saison"],
    temp: "tiede",
    texture: ["fondant", "croquant"],
    price: 3,
    region: "France entière",
    prepMinutes: 25,
    kcal: 560,
    protein: 38,
    carbs: 42,
    fat: 26,
    allergens: ["oeuf"],
    ingredients: ["180g de filet de bœuf haché au couteau", "1 jaune d'œuf", "Échalote, câpres, moutarde, Worcestershire", "Patate douce en frites au four"],
    steps: [
      "Couper la patate douce en bâtonnets, cuire au four 25 min à 200°C",
      "Hacher la viande au couteau finement",
      "Mélanger avec échalote, câpres, moutarde et jaune d'œuf",
      "Servir avec les frites de patate douce",
    ],
    tip: "Utilise une viande très fraîche achetée le jour même chez un bon boucher.",
  },
  {
    id: "din-couscous-legumes-pois-chiches",
    name: "Couscous de légumes et pois chiches",
    meal: "diner",
    diet: ["vegan", "vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["moelleux"],
    price: 1,
    region: "France entière (inspiration maghrébine)",
    prepMinutes: 35,
    kcal: 460,
    protein: 16,
    carbs: 70,
    fat: 12,
    allergens: ["gluten"],
    ingredients: ["Semoule de couscous", "Carotte, navet, courgette, pois chiches", "Bouillon, ras el hanout, raisins secs"],
    steps: [
      "Cuire les légumes et pois chiches dans le bouillon épicé 25 min",
      "Préparer la semoule selon les instructions",
      "Servir les légumes sur la semoule, arroser de bouillon",
    ],
    tip: "Pour version sans gluten, remplace la semoule par du riz ou du quinoa.",
  },
  {
    id: "din-blanquette-legere-dinde",
    name: "Blanquette de dinde allégée et riz",
    meal: "diner",
    diet: ["omnivore"],
    phases: ["maintenance", "surplus"],
    season: ["hiver"],
    temp: "chaud",
    texture: ["fondant", "crémeux"],
    price: 2,
    region: "France entière (classique français)",
    prepMinutes: 40,
    kcal: 480,
    protein: 40,
    carbs: 45,
    fat: 14,
    allergens: ["lactose"],
    ingredients: ["200g de dinde en cubes", "Carotte, champignons, oignon", "Crème légère, bouillon", "Riz basmati"],
    steps: [
      "Faire revenir la dinde, ajouter oignon et carotte",
      "Couvrir de bouillon, mijoter 25 min",
      "Ajouter champignons et crème légère en fin de cuisson",
      "Servir avec du riz",
    ],
    tip: "Version 'fitness' du classique français — remplace la crème entière par de la crème à 4% MG.",
  },

  // ─────────────────────────── COLLATIONS ───────────────────────────
  {
    id: "col-fromage-blanc-miel",
    name: "Fromage blanc, miel et noix",
    meal: "collation",
    diet: ["vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux", "croquant"],
    price: 1,
    region: "France entière",
    prepMinutes: 3,
    kcal: 220,
    protein: 18,
    carbs: 16,
    fat: 9,
    allergens: ["lactose", "fruits-a-coque"],
    ingredients: ["200g de fromage blanc 20%", "1 c. à café de miel", "Quelques noix concassées"],
    steps: ["Mélanger le fromage blanc et le miel", "Ajouter les noix concassées"],
    tip: "Collation express très riche en caséine, idéale en soirée pour la récupération nocturne.",
  },
  {
    id: "col-pomme-beurre-cacahuete",
    name: "Pomme et beurre de cacahuète",
    meal: "collation",
    diet: ["vegan", "vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["automne"],
    temp: "froid",
    texture: ["croquant", "crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 2,
    kcal: 280,
    protein: 8,
    carbs: 30,
    fat: 16,
    allergens: ["arachide"],
    ingredients: ["1 pomme", "1,5 c. à soupe de beurre de cacahuète 100%"],
    steps: ["Couper la pomme en tranches", "Tremper dans le beurre de cacahuète"],
    tip: "Choisis un beurre de cacahuète sans sucre ajouté (liste d'ingrédients = juste 'cacahuètes').",
  },
  {
    id: "col-houmous-batonnets",
    name: "Houmous et bâtonnets de légumes",
    meal: "collation",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux", "croquant"],
    price: 1,
    region: "France entière (inspiration moyen-orientale)",
    prepMinutes: 10,
    kcal: 180,
    protein: 7,
    carbs: 18,
    fat: 9,
    allergens: [],
    ingredients: ["100g de houmous maison ou du commerce", "Carotte, concombre, céleri en bâtonnets"],
    steps: ["Couper les légumes en bâtonnets", "Servir avec le houmous"],
    tip: "Très peu calorique pour le volume — combat bien les fringales en phase de sèche.",
  },
  {
    id: "col-shaker-whey-banane",
    name: "Shaker whey-banane-lait",
    meal: "collation",
    diet: ["vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 3,
    kcal: 320,
    protein: 32,
    carbs: 35,
    fat: 5,
    allergens: ["lactose"],
    ingredients: ["30g de whey", "1 banane", "250ml de lait demi-écrémé"],
    steps: ["Mixer tous les ingrédients", "Servir immédiatement bien frais"],
    tip: "Pratique quand l'appétit manque en surplus calorique — facile à boire même sans faim.",
  },
  {
    id: "col-oeufs-durs-paprika",
    name: "Œufs durs au paprika",
    meal: "collation",
    diet: ["omnivore", "vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 10,
    kcal: 150,
    protein: 13,
    carbs: 1,
    fat: 10,
    allergens: ["oeuf"],
    ingredients: ["2 œufs", "Paprika, sel"],
    steps: ["Cuire les œufs 9-10 min à l'eau bouillante", "Écaler, saupoudrer de paprika et sel"],
    tip: "Se prépare en lot pour 4-5 jours — collation la moins chère du marché en protéines.",
  },
  {
    id: "col-barres-dattes-cacao",
    name: "Barres maison datte-amande-cacao",
    meal: "collation",
    diet: ["vegan", "vegetarien"],
    phases: ["surplus"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["fondant", "croquant"],
    price: 2,
    region: "France entière",
    prepMinutes: 15,
    kcal: 240,
    protein: 6,
    carbs: 28,
    fat: 12,
    allergens: ["fruits-a-coque"],
    ingredients: ["150g de dattes dénoyautées", "100g d'amandes", "2 c. à soupe de cacao non sucré", "Pincée de sel"],
    steps: [
      "Mixer dattes et amandes jusqu'à obtenir une pâte collante",
      "Ajouter le cacao, mixer à nouveau",
      "Étaler dans un moule, tasser et réfrigérer 1h",
      "Découper en barres",
    ],
    tip: "Se conserve 1 semaine au frigo dans une boîte hermétique — parfait pour le sac de sport.",
  },
  {
    id: "col-skyr-cacao-fruits-rouges",
    name: "Skyr cacao et fruits rouges",
    meal: "collation",
    diet: ["vegetarien"],
    phases: ["deficit"],
    season: ["ete"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 4,
    kcal: 160,
    protein: 22,
    carbs: 14,
    fat: 2,
    allergens: ["lactose"],
    ingredients: ["200g de skyr nature", "1 c. à café de cacao non sucré", "Fruits rouges"],
    steps: ["Mélanger le skyr et le cacao", "Ajouter les fruits rouges par-dessus"],
    tip: "Effet 'dessert' avec très peu de calories — excellent pour gérer les envies de sucré en sèche.",
  },
  {
    id: "col-toast-fromage-frais-radis",
    name: "Tartine fromage frais et radis",
    meal: "collation",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["printemps", "ete"],
    temp: "froid",
    texture: ["croquant", "crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 5,
    kcal: 190,
    protein: 10,
    carbs: 20,
    fat: 7,
    allergens: ["gluten", "lactose"],
    ingredients: ["1 tranche de pain complet", "30g de fromage frais (type Saint Môret light)", "Radis émincés", "Ciboulette"],
    steps: ["Tartiner le pain de fromage frais", "Disposer les radis émincés", "Parsemer de ciboulette"],
    tip: "Croquant et frais — parfaite collation de printemps quand les radis sont au top de leur saison.",
  },

  // ─────────────────────────── POST-TRAINING ───────────────────────────
  {
    id: "post-shaker-whey-flocons",
    name: "Shaker whey, flocons d'avoine et flocons de banane",
    meal: "post-training",
    diet: ["vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 3,
    kcal: 380,
    protein: 34,
    carbs: 45,
    fat: 6,
    allergens: ["lactose"],
    ingredients: ["30g de whey", "40g de flocons d'avoine", "1 banane", "300ml d'eau ou lait"],
    steps: ["Mixer tous les ingrédients", "Boire dans les 30-45 min après l'entraînement"],
    tip: "Ratio glucides/protéines idéal pour relancer la synthèse de glycogène et protéique post-effort.",
  },
  {
    id: "post-riz-au-lait-proteine",
    name: "Riz au lait protéiné (façon récupération)",
    meal: "post-training",
    diet: ["vegetarien"],
    phases: ["surplus"],
    season: ["hiver"],
    temp: "chaud",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 25,
    kcal: 420,
    protein: 26,
    carbs: 60,
    fat: 8,
    allergens: ["lactose"],
    ingredients: ["60g de riz rond", "400ml de lait", "20g de whey vanille (hors du feu)", "Cannelle, vanille"],
    steps: [
      "Cuire le riz dans le lait à feu doux 20 min en remuant",
      "Hors du feu, incorporer la whey une fois tiède",
      "Saupoudrer de cannelle",
    ],
    tip: "N'ajoute jamais la whey à chaud (>60°C) pour éviter qu'elle ne coagule.",
  },
  {
    id: "post-poulet-patate-rapide",
    name: "Émincé de poulet et patate douce vapeur (récup express)",
    meal: "post-training",
    diet: ["omnivore"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant"],
    price: 2,
    region: "France entière",
    prepMinutes: 20,
    kcal: 450,
    protein: 42,
    carbs: 48,
    fat: 8,
    allergens: [],
    ingredients: ["180g de poulet émincé", "250g de patate douce", "Sel, épices au choix"],
    steps: [
      "Cuire la patate douce coupée en dés à la vapeur 15 min",
      "Saisir le poulet émincé 6-8 min à la poêle",
      "Assaisonner et servir",
    ],
    tip: "Repas simple et rapide à préparer dès le retour de la salle, sans sauce lourde à digérer.",
  },
  {
    id: "post-smoothie-fruits-proteine",
    name: "Smoothie protéiné fruits rouges et yaourt grec",
    meal: "post-training",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 5,
    kcal: 260,
    protein: 28,
    carbs: 28,
    fat: 4,
    allergens: ["lactose"],
    ingredients: ["150g de yaourt grec 0%", "Fruits rouges surgelés", "1/2 banane", "Eau ou glaçons"],
    steps: ["Mixer tous les ingrédients jusqu'à texture lisse", "Boire frais"],
    tip: "Faible en calories mais riche en protéines — parfait quand tu es en sèche et que tu veux limiter l'apport calorique post-séance.",
  },
  {
    id: "post-galette-riz-jambon-fromage",
    name: "Galettes de riz, jambon et fromage (snack express)",
    meal: "post-training",
    diet: ["omnivore"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["croquant", "fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 5,
    kcal: 280,
    protein: 24,
    carbs: 30,
    fat: 7,
    allergens: ["lactose"],
    ingredients: ["3 galettes de riz soufflé", "2 tranches de jambon blanc", "Fromage type cottage ou tranche light"],
    steps: ["Garnir chaque galette de jambon et fromage", "Manger directement, sans cuisson"],
    tip: "Solution la plus rapide pour un apport rapide en protéines + glucides sans cuisine, parfait en sac de sport.",
  },
  {
    id: "post-tofu-soja-riz-rapide",
    name: "Tofu mariné soja, riz vinaigré rapide",
    meal: "post-training",
    diet: ["vegan", "vegetarien"],
    phases: ["maintenance", "surplus"],
    season: ["toute-saison"],
    temp: "tiede",
    texture: ["fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 15,
    kcal: 400,
    protein: 22,
    carbs: 52,
    fat: 10,
    allergens: ["soja"],
    ingredients: ["200g de tofu ferme", "Riz blanc précuit", "Sauce soja, gingembre", "Huile de sésame"],
    steps: [
      "Mariner le tofu coupé en dés dans la sauce soja et gingembre 5 min",
      "Saisir à la poêle 5 min",
      "Servir sur le riz chaud avec un filet d'huile de sésame",
    ],
    tip: "Le riz précuit en poche micro-ondable est un allié post-training quand le temps manque.",
  },

  // ─────────────────────────── DESSERTS SAINS ───────────────────────────
  {
    id: "des-mousse-chocolat-avocat",
    name: "Mousse au chocolat avocat-cacao (sans sucre ajouté)",
    meal: "dessert",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux"],
    price: 2,
    region: "France entière",
    prepMinutes: 10,
    kcal: 240,
    protein: 4,
    carbs: 18,
    fat: 18,
    allergens: [],
    ingredients: ["1 avocat mûr", "3 c. à soupe de cacao non sucré", "2 c. à soupe de sirop d'érable", "Lait végétal si besoin"],
    steps: [
      "Mixer tous les ingrédients jusqu'à texture lisse et mousseuse",
      "Réfrigérer 30 min avant de servir",
    ],
    tip: "Le goût d'avocat disparaît complètement derrière le cacao — bluffant en texture.",
  },
  {
    id: "des-cookies-proteines-avoine",
    name: "Cookies protéinés avoine et pépites de chocolat",
    meal: "dessert",
    diet: ["vegetarien"],
    phases: ["surplus"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["moelleux", "croquant"],
    price: 1,
    region: "France entière",
    prepMinutes: 25,
    kcal: 180,
    protein: 10,
    carbs: 20,
    fat: 7,
    allergens: ["gluten", "oeuf"],
    ingredients: ["100g de flocons d'avoine mixés", "30g de whey chocolat", "1 œuf", "1 banane écrasée", "Pépites de chocolat noir"],
    steps: [
      "Mélanger tous les ingrédients secs puis humides",
      "Façonner des petits tas sur plaque",
      "Cuire 12 min à 180°C",
    ],
    tip: "Idéal en collation post-training si tu es en surplus calorique — calorique mais riche en protéines.",
  },
  {
    id: "des-compote-pomme-cannelle",
    name: "Compote pomme-cannelle maison (sans sucre ajouté)",
    meal: "dessert",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit"],
    season: ["automne"],
    temp: "tiede",
    texture: ["fondant"],
    price: 1,
    region: "Normandie",
    prepMinutes: 20,
    kcal: 90,
    protein: 0,
    carbs: 22,
    fat: 0,
    allergens: [],
    ingredients: ["4 pommes", "Cannelle", "Un peu d'eau"],
    steps: [
      "Couper les pommes en dés",
      "Cuire à feu doux avec un fond d'eau et cannelle 15 min",
      "Mixer ou écraser grossièrement selon la texture désirée",
    ],
    tip: "Les pommes normandes (Reinette, Golden) donnent naturellement une compote bien sucrée sans rien ajouter.",
  },
  {
    id: "des-yaourt-glace-fruits",
    name: "Yaourt glacé maison aux fruits (sorbet minute)",
    meal: "dessert",
    diet: ["vegetarien"],
    phases: ["deficit"],
    season: ["ete"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 5,
    kcal: 130,
    protein: 12,
    carbs: 16,
    fat: 2,
    allergens: ["lactose"],
    ingredients: ["200g de yaourt grec 0%", "150g de fruits congelés (mangue, fruits rouges)", "1 c. à café de miel"],
    steps: ["Mixer tous les ingrédients jusqu'à consistance de glace", "Servir immédiatement"],
    tip: "Les fruits doivent être congelés pour obtenir la texture glacée sans sorbetière.",
  },
  {
    id: "des-tarte-fine-figues",
    name: "Tarte fine aux figues et miel (pâte fine, peu de sucre)",
    meal: "dessert",
    diet: ["vegetarien"],
    phases: ["surplus"],
    season: ["ete", "automne"],
    temp: "tiede",
    texture: ["croquant", "fondant"],
    price: 2,
    region: "Sud-Ouest / Provence",
    prepMinutes: 30,
    kcal: 260,
    protein: 4,
    carbs: 38,
    fat: 9,
    allergens: ["gluten"],
    ingredients: ["1 pâte feuilletée fine", "6 figues fraîches", "1 c. à soupe de miel", "Romarin (optionnel)"],
    steps: [
      "Étaler la pâte, piquer à la fourchette",
      "Disposer les figues coupées en deux",
      "Napper de miel, cuire 20 min à 200°C",
    ],
    tip: "Les figues du Sud-Ouest et de Provence sont à leur meilleur fin août-septembre.",
  },

  // ─────────────────────────── PETIT-DÉJEUNER (2) ───────────────────────────
  {
    id: "pdj2-shakshuka",
    name: "Shakshuka aux poivrons et tomates",
    meal: "petit-dej",
    diet: ["vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["ete", "automne"],
    temp: "chaud",
    texture: ["fondant"],
    price: 1,
    region: "France entière (inspiration maghrébine)",
    prepMinutes: 20,
    kcal: 320,
    protein: 18,
    carbs: 16,
    fat: 18,
    allergens: ["oeuf"],
    ingredients: ["3 œufs", "Poivron rouge, oignon, tomates concassées", "Cumin, paprika, ail", "Huile d'olive, coriandre"],
    steps: [
      "Faire revenir oignon, ail et poivron 5 min",
      "Ajouter les tomates et les épices, mijoter 10 min",
      "Creuser des nids, casser les œufs dedans, couvrir 5-6 min",
      "Parsemer de coriandre fraîche",
    ],
    tip: "Se mange directement à la poêle avec du pain — convivial pour un brunch.",
  },
  {
    id: "pdj2-overnight-oats",
    name: "Overnight oats banane-cacao",
    meal: "petit-dej",
    diet: ["vegan", "vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 5,
    kcal: 410,
    protein: 16,
    carbs: 58,
    fat: 12,
    allergens: [],
    ingredients: ["50g de flocons d'avoine", "200ml de lait végétal", "1 banane écrasée", "1 c. à soupe de cacao non sucré", "1 c. à café de graines de chia"],
    steps: [
      "Mélanger tous les ingrédients dans un bocal",
      "Réfrigérer toute la nuit",
      "Mélanger et déguster froid le matin",
    ],
    tip: "Prépare 3-4 bocaux le dimanche pour toute la semaine — zéro effort le matin.",
  },
  {
    id: "pdj2-tartines-avocat-saumon",
    name: "Tartines avocat et saumon fumé",
    meal: "petit-dej",
    diet: ["pescetarien"],
    phases: ["maintenance", "surplus"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["croquant", "fondant"],
    price: 3,
    region: "Bretagne / Norvège",
    prepMinutes: 8,
    kcal: 420,
    protein: 22,
    carbs: 28,
    fat: 24,
    allergens: ["gluten", "poisson"],
    ingredients: ["2 tranches de pain complet", "1/2 avocat", "2 tranches de saumon fumé", "Citron, aneth, poivre"],
    steps: [
      "Toaster le pain",
      "Écraser l'avocat avec citron et poivre, étaler",
      "Disposer le saumon fumé, parsemer d'aneth",
    ],
    tip: "Riche en oméga-3 — un excellent départ avant une séance du matin.",
  },
  {
    id: "pdj2-porridge-quinoa",
    name: "Porridge de quinoa pomme-cannelle",
    meal: "petit-dej",
    diet: ["vegan", "vegetarien"],
    phases: ["maintenance"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 15,
    kcal: 360,
    protein: 11,
    carbs: 56,
    fat: 9,
    allergens: [],
    ingredients: ["80g de quinoa cru", "200ml de lait végétal", "1 pomme coupée en dés", "Cannelle, vanille"],
    steps: [
      "Cuire le quinoa dans le lait végétal 15 min à feu doux",
      "Ajouter la pomme en dés à mi-cuisson",
      "Saupoudrer de cannelle et vanille en fin de cuisson",
    ],
    tip: "Le quinoa apporte des protéines complètes — alternative intéressante à l'avoine.",
  },
  {
    id: "pdj2-pancakes-sarrasin",
    name: "Pancakes de sarrasin sans gluten",
    meal: "petit-dej",
    diet: ["vegetarien", "vegan"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["moelleux"],
    price: 1,
    region: "Bretagne",
    prepMinutes: 15,
    kcal: 380,
    protein: 12,
    carbs: 54,
    fat: 10,
    allergens: [],
    ingredients: ["100g de farine de sarrasin", "200ml de lait végétal", "1 c. à café de levure", "1 c. à soupe d'huile", "Fruits rouges pour servir"],
    steps: [
      "Mélanger tous les ingrédients pour une pâte lisse",
      "Cuire des petites portions à la poêle chaude, 2 min par face",
      "Servir avec fruits rouges et un filet de miel ou sirop d'agave",
    ],
    tip: "100% sans gluten naturellement — bonne option pour varier sans avoine.",
  },

  // ─────────────────────────── DÉJEUNER (2) ───────────────────────────
  {
    id: "dej2-bowl-falafels",
    name: "Bowl de falafels maison et taboulé",
    meal: "dejeuner",
    diet: ["vegan", "vegetarien"],
    phases: ["maintenance", "surplus"],
    season: ["ete"],
    temp: "tiede",
    texture: ["croquant", "fondant"],
    price: 1,
    region: "France entière (inspiration moyen-orientale)",
    prepMinutes: 35,
    kcal: 520,
    protein: 18,
    carbs: 62,
    fat: 20,
    allergens: ["gluten"],
    ingredients: ["200g de pois chiches trempés", "Persil, menthe, cumin, ail", "Semoule de couscous", "Tomate, concombre, citron"],
    steps: [
      "Mixer les pois chiches avec ail, cumin et herbes",
      "Façonner des boulettes, cuire au four 20 min à 200°C",
      "Préparer le taboulé avec semoule, tomate, concombre et citron",
      "Dresser falafels et taboulé ensemble",
    ],
    tip: "Cuits au four plutôt qu'en friture — beaucoup moins gras, tout aussi croustillant.",
  },
  {
    id: "dej2-saumon-teriyaki",
    name: "Saumon teriyaki et riz vinaigré",
    meal: "dejeuner",
    diet: ["pescetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant"],
    price: 3,
    region: "France entière (inspiration japonaise)",
    prepMinutes: 20,
    kcal: 560,
    protein: 36,
    carbs: 52,
    fat: 20,
    allergens: ["poisson", "soja"],
    ingredients: ["150g de saumon", "Sauce soja, miel, gingembre, ail", "Riz blanc", "Graines de sésame"],
    steps: [
      "Mariner le saumon dans soja, miel, gingembre et ail 10 min",
      "Cuire le riz",
      "Saisir le saumon à la poêle 4 min par face en arrosant de marinade",
      "Servir sur le riz, parsemer de sésame",
    ],
    tip: "La marinade caramélise vite — surveille la cuisson pour éviter qu'elle ne brûle.",
  },
  {
    id: "dej2-chili-sin-carne",
    name: "Chili sin carne (haricots rouges)",
    meal: "dejeuner",
    diet: ["vegan", "vegetarien"],
    phases: ["maintenance", "surplus"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["fondant"],
    price: 1,
    region: "France entière (inspiration tex-mex)",
    prepMinutes: 30,
    kcal: 440,
    protein: 20,
    carbs: 58,
    fat: 10,
    allergens: [],
    ingredients: ["240g de haricots rouges cuits", "Tomates concassées, oignon, poivron", "Piment, cumin, paprika fumé", "Riz pour servir"],
    steps: [
      "Faire revenir oignon et poivron 5 min",
      "Ajouter tomates, épices et haricots, mijoter 20 min",
      "Servir sur riz blanc ou complet",
    ],
    tip: "Encore meilleur réchauffé le lendemain — fais-en une grande quantité.",
  },
  {
    id: "dej2-salade-quinoa-feta",
    name: "Salade de quinoa, feta et grenade",
    meal: "dejeuner",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["automne", "hiver"],
    temp: "froid",
    texture: ["croquant", "fondant"],
    price: 2,
    region: "Méditerranée",
    prepMinutes: 20,
    kcal: 410,
    protein: 16,
    carbs: 42,
    fat: 18,
    allergens: ["lactose"],
    ingredients: ["150g de quinoa cuit", "60g de feta", "Graines de grenade", "Roquette, huile d'olive, citron"],
    steps: [
      "Mélanger le quinoa avec huile d'olive et citron",
      "Ajouter roquette et graines de grenade",
      "Émietter la feta sur le dessus",
    ],
    tip: "Les graines de grenade apportent du croquant et une touche acidulée bienvenue.",
  },
  {
    id: "dej2-burger-poulet-maison",
    name: "Burger de poulet maison, pain complet",
    meal: "dejeuner",
    diet: ["omnivore"],
    phases: ["surplus"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["croquant", "fondant"],
    price: 2,
    region: "France entière",
    prepMinutes: 25,
    kcal: 580,
    protein: 42,
    carbs: 48,
    fat: 22,
    allergens: ["gluten"],
    ingredients: ["180g de blanc de poulet émincé", "1 pain à burger complet", "Salade, tomate, oignon rouge", "Sauce yaourt-moutarde"],
    steps: [
      "Mariner et griller le poulet 6-7 min par face",
      "Toaster légèrement le pain",
      "Garnir avec salade, tomate, oignon et sauce",
      "Assembler le burger",
    ],
    tip: "Remplace la mayo classique par une sauce au yaourt — même onctuosité, moins de calories.",
  },
  {
    id: "dej2-riz-cantonais-crevettes",
    name: "Riz cantonais aux crevettes et légumes",
    meal: "dejeuner",
    diet: ["pescetarien"],
    phases: ["maintenance", "surplus"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant"],
    price: 2,
    region: "France entière (inspiration asiatique)",
    prepMinutes: 20,
    kcal: 480,
    protein: 28,
    carbs: 58,
    fat: 12,
    allergens: ["crustaces", "oeuf", "soja"],
    ingredients: ["200g de crevettes décortiquées", "Riz blanc cuit (idéalement de la veille)", "Petits pois, carotte, œuf", "Sauce soja, huile de sésame"],
    steps: [
      "Faire revenir les crevettes 3 min, réserver",
      "Faire sauter le riz avec petits pois et carotte",
      "Ajouter l'œuf battu, remuer pour l'incorporer",
      "Réunir avec les crevettes, arroser de sauce soja",
    ],
    tip: "Le riz de la veille (froid) se fait sauter sans coller — bien meilleur résultat que du riz chaud.",
  },

  // ─────────────────────────── DÎNER (2) ───────────────────────────
  {
    id: "din2-soupe-miso-tofu",
    name: "Soupe miso au tofu et algues wakamé",
    meal: "diner",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit"],
    season: ["hiver", "automne"],
    temp: "chaud",
    texture: ["fondant"],
    price: 1,
    region: "France entière (inspiration japonaise)",
    prepMinutes: 15,
    kcal: 180,
    protein: 12,
    carbs: 10,
    fat: 8,
    allergens: ["soja"],
    ingredients: ["1 c. à soupe de pâte miso", "100g de tofu ferme en dés", "Algues wakamé réhydratées", "Oignon vert"],
    steps: [
      "Faire chauffer de l'eau sans bouillir fortement",
      "Diluer la pâte miso hors du feu vif",
      "Ajouter tofu et algues, réchauffer 2-3 min",
      "Parsemer d'oignon vert",
    ],
    tip: "Ne fais jamais bouillir le miso à gros bouillons — ça détruit les probiotiques et l'arôme.",
  },
  {
    id: "din2-poelee-boeuf-legumes",
    name: "Poêlée de bœuf et légumes croquants au gingembre",
    meal: "diner",
    diet: ["omnivore"],
    phases: ["maintenance", "surplus"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["croquant", "fondant"],
    price: 2,
    region: "France entière (inspiration asiatique)",
    prepMinutes: 18,
    kcal: 460,
    protein: 36,
    carbs: 26,
    fat: 22,
    allergens: ["soja"],
    ingredients: ["180g de bœuf en lanières", "Poivron, brocoli, carotte", "Gingembre, ail, sauce soja", "Huile de sésame"],
    steps: [
      "Saisir le bœuf à feu vif 2-3 min, réserver",
      "Faire sauter les légumes 5 min avec gingembre et ail",
      "Réunir bœuf et légumes, arroser de sauce soja",
      "Finir avec un filet d'huile de sésame",
    ],
    tip: "Coupe le bœuf très fin et contre les fibres pour qu'il reste tendre à cuisson rapide.",
  },
  {
    id: "din2-tarte-poireaux-legere",
    name: "Tarte aux poireaux sans pâte",
    meal: "diner",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["automne", "hiver"],
    temp: "tiede",
    texture: ["fondant", "moelleux"],
    price: 1,
    region: "France entière",
    prepMinutes: 35,
    kcal: 320,
    protein: 20,
    carbs: 14,
    fat: 20,
    allergens: ["oeuf", "lactose"],
    ingredients: ["2 poireaux", "4 œufs", "150ml de lait", "50g de comté râpé", "Noix de muscade"],
    steps: [
      "Émincer et faire fondre les poireaux 10 min à la poêle",
      "Battre œufs et lait, assaisonner à la muscade",
      "Verser dans un plat avec poireaux et comté",
      "Cuire 25 min à 180°C",
    ],
    tip: "Sans pâte, c'est un dîner léger en glucides mais qui cale bien grâce aux œufs.",
  },
  {
    id: "din2-curry-pois-coco-epinards",
    name: "Curry de pois chiches, épinards et lait de coco",
    meal: "diner",
    diet: ["vegan", "vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["crémeux"],
    price: 1,
    region: "France entière (inspiration indienne)",
    prepMinutes: 25,
    kcal: 380,
    protein: 16,
    carbs: 40,
    fat: 16,
    allergens: [],
    ingredients: ["200g de pois chiches cuits", "150g d'épinards frais", "150ml de lait de coco léger", "Curry, curcuma, ail, oignon"],
    steps: [
      "Faire revenir oignon et ail, ajouter les épices",
      "Ajouter pois chiches et lait de coco, mijoter 10 min",
      "Incorporer les épinards en fin de cuisson jusqu'à ce qu'ils tombent",
    ],
    tip: "Le lait de coco léger réduit les calories sans perdre le crémeux du plat.",
  },
  {
    id: "din2-truite-amandes",
    name: "Truite meunière aux amandes",
    meal: "diner",
    diet: ["pescetarien"],
    phases: ["maintenance", "surplus"],
    season: ["printemps", "ete"],
    temp: "chaud",
    texture: ["fondant", "croquant"],
    price: 2,
    region: "France entière (classique)",
    prepMinutes: 15,
    kcal: 420,
    protein: 34,
    carbs: 6,
    fat: 28,
    allergens: ["poisson", "fruits-a-coque", "gluten"],
    ingredients: ["1 truite entière ou filet", "Farine pour fariner légèrement", "Amandes effilées", "Beurre, citron, persil"],
    steps: [
      "Fariner légèrement la truite",
      "Cuire au beurre 4 min par face",
      "Faire dorer les amandes effilées dans le même beurre",
      "Arroser de citron et parsemer d'amandes et persil",
    ],
    tip: "Pour une version sans gluten, remplace la farine de blé par de la farine de riz.",
  },
  {
    id: "din2-buddha-bowl-saumon-froid",
    name: "Buddha bowl froid au saumon fumé",
    meal: "diner",
    diet: ["pescetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete"],
    temp: "froid",
    texture: ["fondant", "croquant"],
    price: 3,
    region: "France entière",
    prepMinutes: 15,
    kcal: 420,
    protein: 26,
    carbs: 34,
    fat: 20,
    allergens: ["poisson"],
    ingredients: ["100g de saumon fumé", "Quinoa cuit, concombre, avocat", "Roquette, citron, huile d'olive"],
    steps: [
      "Disposer quinoa, concombre et avocat dans un bol",
      "Ajouter le saumon fumé en lanières",
      "Arroser d'huile d'olive et citron, ajouter la roquette",
    ],
    tip: "Aucune cuisson nécessaire — parfait pour un dîner d'été rapide après une journée chargée.",
  },

  // ─────────────────────────── COLLATIONS (2) ───────────────────────────
  {
    id: "col2-edamame-sel",
    name: "Edamame vapeur au sel",
    meal: "collation",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete"],
    temp: "chaud",
    texture: ["croquant"],
    price: 1,
    region: "France entière (inspiration japonaise)",
    prepMinutes: 6,
    kcal: 150,
    protein: 13,
    carbs: 10,
    fat: 6,
    allergens: ["soja"],
    ingredients: ["200g d'edamame surgelés", "Fleur de sel"],
    steps: ["Cuire les edamame à la vapeur ou à l'eau bouillante 5 min", "Saler et déguster directement dans la cosse"],
    tip: "Très riche en protéines végétales pour une collation — rare pour un légume.",
  },
  {
    id: "col2-smoothie-vert",
    name: "Smoothie vert épinard-pomme-citron",
    meal: "collation",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit"],
    season: ["printemps"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 5,
    kcal: 110,
    protein: 2,
    carbs: 26,
    fat: 1,
    allergens: [],
    ingredients: ["Poignée d'épinards frais", "1 pomme", "Jus de citron", "Eau, glaçons"],
    steps: ["Mixer tous les ingrédients jusqu'à texture lisse", "Servir bien frais"],
    tip: "Une collation très basse en calories, idéale pour gérer une fringale en sèche sans plomber le bilan.",
  },
  {
    id: "col2-toast-houmous-radis",
    name: "Toast houmous, radis et graines",
    meal: "collation",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["printemps", "ete"],
    temp: "froid",
    texture: ["croquant", "crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 5,
    kcal: 200,
    protein: 7,
    carbs: 24,
    fat: 8,
    allergens: ["gluten"],
    ingredients: ["1 tranche de pain complet", "30g de houmous", "Radis émincés", "Graines de courge"],
    steps: ["Tartiner le pain de houmous", "Disposer les radis émincés", "Parsemer de graines"],
    tip: "Le houmous maison (pois chiches + tahini + citron) est bien moins gras que les versions industrielles.",
  },
  {
    id: "col2-yaourt-grec-miel-noix",
    name: "Yaourt grec, miel et noix concassées",
    meal: "collation",
    diet: ["vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux", "croquant"],
    price: 1,
    region: "France entière",
    prepMinutes: 3,
    kcal: 260,
    protein: 16,
    carbs: 18,
    fat: 14,
    allergens: ["lactose", "fruits-a-coque"],
    ingredients: ["200g de yaourt grec entier", "1 c. à café de miel", "Noix concassées"],
    steps: ["Mélanger le yaourt et le miel", "Ajouter les noix concassées par-dessus"],
    tip: "Le yaourt grec entier (pas 0%) est nécessaire ici pour les calories supplémentaires en surplus.",
  },
  {
    id: "col2-mix-fruits-secs-maison",
    name: "Mix de fruits secs et oléagineux maison",
    meal: "collation",
    diet: ["vegan", "vegetarien"],
    phases: ["surplus"],
    season: ["automne", "hiver"],
    temp: "froid",
    texture: ["croquant"],
    price: 2,
    region: "France entière",
    prepMinutes: 2,
    kcal: 290,
    protein: 8,
    carbs: 22,
    fat: 19,
    allergens: ["fruits-a-coque"],
    ingredients: ["15g d'amandes", "15g de noix de cajou", "15g de raisins secs", "15g d'abricots secs"],
    steps: ["Mélanger tous les ingrédients dans un petit contenant", "Emporter facilement au travail ou en salle"],
    tip: "Pèse les portions à l'avance en sachets — c'est très calorique vite si on se sert au pif.",
  },

  // ─────────────────────────── POST-TRAINING (2) ───────────────────────────
  {
    id: "post2-skyr-fruits-rouges-granola",
    name: "Skyr, fruits rouges et granola (récup rapide)",
    meal: "post-training",
    diet: ["vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux", "croquant"],
    price: 1,
    region: "France entière",
    prepMinutes: 4,
    kcal: 320,
    protein: 30,
    carbs: 36,
    fat: 6,
    allergens: ["lactose"],
    ingredients: ["200g de skyr nature", "Fruits rouges surgelés", "30g de granola pauvre en sucre"],
    steps: ["Verser le skyr dans un bol", "Ajouter fruits rouges et granola"],
    tip: "Le skyr reste l'option la plus riche en protéines pour le moins de calories en post-training.",
  },
  {
    id: "post2-wrap-thon-riz",
    name: "Wrap thon-riz (récup post-séance)",
    meal: "post-training",
    diet: ["pescetarien"],
    phases: ["maintenance", "surplus"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 8,
    kcal: 420,
    protein: 32,
    carbs: 50,
    fat: 8,
    allergens: ["gluten", "poisson"],
    ingredients: ["1 galette de blé complet", "1 boîte de thon au naturel", "Riz blanc cuit", "Yaourt, citron, ciboulette"],
    steps: [
      "Égoutter le thon, mélanger avec un peu de yaourt et citron",
      "Garnir la galette de riz puis du mélange au thon",
      "Rouler serré",
    ],
    tip: "Se prépare la veille et se mange froid directement en sortant de la salle.",
  },
  {
    id: "post2-shaker-caseine-banane",
    name: "Shaker caséine-banane (récup nocturne)",
    meal: "post-training",
    diet: ["vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 3,
    kcal: 260,
    protein: 28,
    carbs: 24,
    fat: 4,
    allergens: ["lactose"],
    ingredients: ["30g de caséine micellaire", "1/2 banane", "250ml de lait"],
    steps: ["Mixer tous les ingrédients", "Boire environ 1h avant le coucher après une séance du soir"],
    tip: "La caséine digère lentement — idéale pour une séance en fin de journée, limite le catabolisme nocturne.",
  },
  {
    id: "post2-patate-douce-oeufs-rapide",
    name: "Patate douce et œufs brouillés (récup express)",
    meal: "post-training",
    diet: ["vegetarien"],
    phases: ["maintenance", "surplus"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 15,
    kcal: 380,
    protein: 22,
    carbs: 42,
    fat: 12,
    allergens: ["oeuf"],
    ingredients: ["200g de patate douce", "3 œufs", "Sel, paprika"],
    steps: [
      "Cuire la patate douce coupée en dés à la vapeur ou au micro-ondes 8-10 min",
      "Brouiller les œufs à la poêle",
      "Servir ensemble, assaisonner",
    ],
    tip: "Le micro-ondes (couvert, quelques minutes) cuit la patate douce presque aussi bien que la vapeur, en bien moins de temps.",
  },

  // ─────────────────────────── DESSERTS SAINS (2) ───────────────────────────
  {
    id: "des2-banane-glacee-chocolat",
    name: "Banane glacée enrobée de chocolat noir",
    meal: "dessert",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete"],
    temp: "froid",
    texture: ["croquant", "fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 10,
    kcal: 140,
    protein: 2,
    carbs: 26,
    fat: 5,
    allergens: [],
    ingredients: ["1 banane coupée en rondelles", "30g de chocolat noir 85% fondu"],
    steps: [
      "Tremper chaque rondelle de banane dans le chocolat fondu",
      "Disposer sur une plaque, congeler 1h",
    ],
    tip: "Le chocolat à 85% a beaucoup moins de sucre que le chocolat au lait classique.",
  },
  {
    id: "des2-mug-cake-proteine",
    name: "Mug cake protéiné chocolat (2 minutes au micro-ondes)",
    meal: "dessert",
    diet: ["vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["moelleux"],
    price: 1,
    region: "France entière",
    prepMinutes: 5,
    kcal: 220,
    protein: 24,
    carbs: 18,
    fat: 7,
    allergens: ["oeuf", "lactose"],
    ingredients: ["30g de whey chocolat", "1 œuf", "1 c. à soupe de lait", "1/2 c. à café de levure", "Pépites de chocolat (optionnel)"],
    steps: [
      "Mélanger tous les ingrédients directement dans un mug",
      "Cuire 90 secondes à 800W au micro-ondes",
      "Laisser tiédir 1 min avant de déguster",
    ],
    tip: "Ne dépasse pas 2 min de cuisson — ça devient vite sec et caoutchouteux.",
  },
  {
    id: "des2-salade-fruits-menthe",
    name: "Salade de fruits frais à la menthe",
    meal: "dessert",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit"],
    season: ["ete"],
    temp: "froid",
    texture: ["fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 10,
    kcal: 100,
    protein: 1,
    carbs: 24,
    fat: 0,
    allergens: [],
    ingredients: ["Fraises, melon, kiwi, raisins", "Quelques feuilles de menthe fraîche", "Jus de citron"],
    steps: ["Couper tous les fruits en morceaux", "Mélanger avec citron et menthe ciselée", "Réfrigérer 30 min avant de servir"],
    tip: "Le citron empêche les fruits coupés (pomme, banane) de brunir s'il y en a dans le mélange.",
  },
  {
    id: "des2-fromage-blanc-speculoos",
    name: "Fromage blanc écrasé de spéculoos (version light)",
    meal: "dessert",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["automne", "hiver"],
    temp: "froid",
    texture: ["crémeux", "croquant"],
    price: 1,
    region: "France entière (inspiration belge)",
    prepMinutes: 5,
    kcal: 180,
    protein: 14,
    carbs: 20,
    fat: 5,
    allergens: ["lactose", "gluten"],
    ingredients: ["200g de fromage blanc 3%", "2 spéculoos écrasés", "Cannelle"],
    steps: ["Verser le fromage blanc dans un bol", "Écraser les spéculoos par-dessus", "Saupoudrer de cannelle"],
    tip: "Avec seulement 2 biscuits, le craquant reste là sans faire exploser les calories.",
  },

  // ─────────────────────────── RECETTES EXCLUSIVES ───────────────────────────
  // Signature EP Coaching — débloquées par l'abonnement ou en accumulant des
  // points (voir lib/gamification.ts, FEATURE_UNLOCK_POINTS.exclusive_recipes).
  {
    id: "excl-bowl-saumon-teriyaki",
    name: "Bowl saumon teriyaki maison, riz vinaigré",
    meal: "dejeuner",
    diet: ["pescetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant", "croquant"],
    price: 3,
    region: "France entière (inspiration japonaise)",
    prepMinutes: 30,
    kcal: 650,
    protein: 42,
    carbs: 68,
    fat: 22,
    allergens: ["poisson", "soja", "gluten"],
    ingredients: [
      "180g de pavé de saumon",
      "150g de riz rond cuit",
      "1 càs de vinaigre de riz",
      "2 càs de sauce soja",
      "1 càs de miel",
      "1 càs de mirin (ou vinaigre + sucre)",
      "1/2 avocat",
      "1/2 concombre",
      "Graines de sésame",
    ],
    steps: [
      "Mélanger soja, miel et mirin, faire mariner le saumon 10 min",
      "Saisir le saumon à la poêle 3-4 min par face jusqu'à caramélisation de la sauce",
      "Assaisonner le riz tiède avec le vinaigre de riz",
      "Dresser le riz en bol, ajouter saumon, avocat et concombre en lamelles",
      "Parsemer de sésame et d'un filet de sauce restante",
    ],
    tip: "Sors le saumon du frigo 15 min avant cuisson pour une cuisson plus régulière à cœur.",
    exclusive: true,
  },
  {
    id: "excl-tartare-boeuf-mangue",
    name: "Tartare de bœuf, mangue et coriandre",
    meal: "diner",
    diet: ["omnivore"],
    phases: ["maintenance", "deficit"],
    season: ["printemps", "ete"],
    temp: "froid",
    texture: ["fondant"],
    price: 3,
    region: "France entière (inspiration asiatique)",
    prepMinutes: 20,
    kcal: 420,
    protein: 38,
    carbs: 18,
    fat: 20,
    allergens: [],
    ingredients: [
      "200g de filet de bœuf qualité tartare",
      "1/2 mangue mûre en petits dés",
      "1/2 échalote ciselée",
      "Coriandre fraîche",
      "1 càs de sauce soja",
      "Jus d'1/2 citron vert",
      "1 filet d'huile de sésame",
      "Piment frais (optionnel)",
    ],
    steps: [
      "Couper le bœuf au couteau en petits dés réguliers (jamais au mixeur, ça l'écrase)",
      "Mélanger avec mangue, échalote et coriandre ciselée",
      "Assaisonner avec soja, citron vert et huile de sésame juste avant de servir",
      "Dresser à l'aide d'un cercle, ajouter le piment si tu aimes le relevé",
    ],
    tip: "Demande à ton boucher un morceau frais du jour spécifiquement destiné au tartare.",
    exclusive: true,
  },
  {
    id: "excl-pancakes-proteines-myrtilles",
    name: "Pancakes protéinés moelleux, myrtilles et beurre de cacahuète",
    meal: "petit-dej",
    diet: ["vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["moelleux", "fondant"],
    price: 2,
    region: "France entière",
    prepMinutes: 15,
    kcal: 520,
    protein: 38,
    carbs: 52,
    fat: 16,
    allergens: ["oeuf", "lactose", "gluten", "arachide"],
    ingredients: [
      "50g de flocons d'avoine mixés en farine",
      "30g de whey vanille",
      "2 œufs",
      "100g de fromage blanc",
      "1/2 sachet de levure chimique",
      "80g de myrtilles",
      "1 càs de beurre de cacahuète",
    ],
    steps: [
      "Mixer flocons d'avoine, whey, œufs, fromage blanc et levure jusqu'à pâte lisse",
      "Laisser reposer 5 min pour que la pâte épaississe",
      "Cuire à feu doux dans une poêle légèrement huilée, 2-3 min par face",
      "Empiler les pancakes, parsemer de myrtilles et napper de beurre de cacahuète fondu",
    ],
    tip: "Pâte trop liquide ? Ajoute une cuillère de flocons d'avoine en plus plutôt que de la whey — ça évite le goût trop poudreux.",
    exclusive: true,
  },
  {
    id: "excl-curry-vert-poulet-lait-coco",
    name: "Curry vert de poulet, lait de coco léger et riz basmati",
    meal: "diner",
    diet: ["omnivore"],
    phases: ["maintenance", "surplus"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["fondant", "onctueux"],
    price: 2,
    region: "France entière (inspiration thaïe)",
    prepMinutes: 35,
    kcal: 580,
    protein: 44,
    carbs: 55,
    fat: 18,
    allergens: [],
    ingredients: [
      "200g de blanc de poulet en cubes",
      "200ml de lait de coco light",
      "1 càs de pâte de curry vert",
      "1 poivron rouge",
      "1 poignée de haricots verts",
      "150g de riz basmati cuit",
      "Basilic thaï ou coriandre",
      "Jus d'1/2 citron vert",
    ],
    steps: [
      "Faire revenir la pâte de curry 1 min dans un filet d'huile pour la réveiller",
      "Ajouter le poulet, saisir 5 min",
      "Verser le lait de coco, laisser mijoter 10 min",
      "Ajouter poivron et haricots verts, cuire 8-10 min jusqu'à tendreté",
      "Servir sur le riz, finir avec citron vert et herbes fraîches",
    ],
    tip: "Le lait de coco light divise les lipides par deux sans vraiment changer le goût en cuisine épicée.",
    exclusive: true,
  },
  {
    id: "excl-energy-balls-dattes-cacao",
    name: "Energy balls dattes, cacao et amandes (sans cuisson)",
    meal: "collation",
    diet: ["vegan"],
    phases: ["surplus", "maintenance", "deficit"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["fondant", "croquant"],
    price: 2,
    region: "France entière",
    prepMinutes: 15,
    kcal: 160,
    protein: 5,
    carbs: 18,
    fat: 8,
    allergens: ["fruits-a-coque"],
    ingredients: [
      "150g de dattes dénoyautées",
      "60g d'amandes",
      "2 càs de cacao non sucré",
      "1 càs d'huile de coco",
      "Pincée de sel",
      "Noix de coco râpée pour l'enrobage",
    ],
    steps: [
      "Mixer dattes et amandes jusqu'à obtenir une pâte collante",
      "Ajouter cacao, huile de coco et sel, mixer à nouveau",
      "Façonner des boules d'environ 20g",
      "Rouler dans la noix de coco râpée, réserver au frais 30 min",
    ],
    tip: "Trempe les dattes 10 min dans l'eau tiède si elles sont un peu sèches, pour que la pâte se tienne mieux.",
    exclusive: true,
  },
  {
    id: "excl-poke-bowl-thon-edamame",
    name: "Poke bowl thon mariné, edamame et riz vinaigré",
    meal: "post-training",
    diet: ["pescetarien"],
    phases: ["surplus", "maintenance"],
    season: ["printemps", "ete"],
    temp: "froid",
    texture: ["fondant", "croquant"],
    price: 3,
    region: "France entière (inspiration hawaïenne)",
    prepMinutes: 20,
    kcal: 610,
    protein: 46,
    carbs: 62,
    fat: 18,
    allergens: ["poisson", "soja"],
    ingredients: [
      "180g de thon qualité tartare",
      "150g de riz cuit vinaigré",
      "80g d'edamame écossés",
      "1/4 de mangue en dés",
      "1/4 de concombre en dés",
      "2 càs de sauce soja",
      "1 càt d'huile de sésame",
      "Sésame grillé",
    ],
    steps: [
      "Couper le thon en cubes, mariner 5 min dans soja et huile de sésame",
      "Dresser le riz vinaigré en fond de bol",
      "Disposer thon, edamame, mangue et concombre en sections",
      "Parsemer de sésame grillé et d'un trait de sauce restante",
    ],
    tip: "Parfait post-séance : ratio glucides/protéines pensé pour relancer la récupération sans lourdeur.",
    exclusive: true,
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────

export function macroBadge(r: Recipe): string {
  return `${r.kcal} kcal · P ${r.protein}g · G ${r.carbs}g · L ${r.fat}g`;
}
