// ── Types ──────────────────────────────────────────────────────────────────

export type MealType =
  | "petit-dej"
  | "dejeuner"
  | "diner"
  | "collation"
  | "post-training"
  | "dessert";

export type Diet = "omnivore" | "vegetarien" | "vegan" | "pescetarien";

export type Phase = "surplus" | "maintenance" | "deficit";

export type Season = "printemps" | "ete" | "automne" | "hiver" | "toute-saison";

export type Temp = "chaud" | "froid" | "tiede";

export type Allergen =
  | "gluten"
  | "lactose"
  | "oeuf"
  | "fruits-a-coque"
  | "poisson"
  | "crustaces"
  | "soja"
  | "arachide";

export interface Recipe {
  id: string;
  name: string;
  meal: MealType;
  diet: Diet[];
  phases: Phase[];
  season: Season[];
  temp: Temp;
  texture: string[];
  price: 1 | 2 | 3; // € / €€ / €€€
  region: string;
  prepMinutes: number;
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  allergens: Allergen[];
  ingredients: string[];
  steps: string[];
  tip: string;
}

// ── Labels pour l'UI ──────────────────────────────────────────────────────

export const MEAL_LABELS: Record<MealType, string> = {
  "petit-dej": "Petit-déjeuner",
  dejeuner: "Déjeuner",
  diner: "Dîner",
  collation: "Collation",
  "post-training": "Post-training",
  dessert: "Dessert",
};

export const DIET_LABELS: Record<Diet, string> = {
  omnivore: "Omnivore",
  vegetarien: "Végétarien",
  vegan: "Vegan",
  pescetarien: "Pescétarien",
};

export const PHASE_LABELS: Record<Phase, string> = {
  surplus: "Surplus (prise de masse)",
  maintenance: "Maintenance",
  deficit: "Déficit (sèche)",
};

export const SEASON_LABELS: Record<Season, string> = {
  printemps: "Printemps",
  ete: "Été",
  automne: "Automne",
  hiver: "Hiver",
  "toute-saison": "Toute saison",
};

export const TEMP_LABELS: Record<Temp, string> = {
  chaud: "Chaud",
  froid: "Froid",
  tiede: "Tiède",
};

export const ALLERGEN_LABELS: Record<Allergen, string> = {
  gluten: "Gluten",
  lactose: "Lactose",
  oeuf: "Œuf",
  "fruits-a-coque": "Fruits à coque",
  poisson: "Poisson",
  crustaces: "Crustacés",
  soja: "Soja",
  arachide: "Arachide",
};

export const PRICE_LABELS: Record<1 | 2 | 3, string> = {
  1: "€",
  2: "€€",
  3: "€€€",
};

// ── Base de recettes ──────────────────────────────────────────────────────

export const RECIPES: Recipe[] = [
  // ─────────────────────────── PETIT-DÉJEUNER ───────────────────────────
  {
    id: "pdj-omelette-epinards",
    name: "Omelette aux épinards et comté",
    meal: "petit-dej",
    diet: ["omnivore", "vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant", "moelleux"],
    price: 1,
    region: "France entière",
    prepMinutes: 10,
    kcal: 380,
    protein: 32,
    carbs: 4,
    fat: 26,
    allergens: ["oeuf", "lactose"],
    ingredients: ["3 œufs", "Poignée d'épinards frais", "30g de comté râpé", "Sel, poivre, muscade"],
    steps: [
      "Faire tomber les épinards 2 min à la poêle",
      "Battre les œufs, ajouter le comté",
      "Verser sur les épinards, cuire 3-4 min à feu doux",
      "Plier en deux, servir immédiatement",
    ],
    tip: "Ajoute une tranche de pain de seigle grillé si tu es en surplus.",
  },
  {
    id: "pdj-porridge-fruits-rouges",
    name: "Porridge d'avoine, fruits rouges et amandes",
    meal: "petit-dej",
    diet: ["vegetarien", "vegan"],
    phases: ["surplus", "maintenance"],
    season: ["ete", "printemps"],
    temp: "chaud",
    texture: ["crémeux", "croquant"],
    price: 1,
    region: "France entière",
    prepMinutes: 8,
    kcal: 420,
    protein: 14,
    carbs: 58,
    fat: 14,
    allergens: ["fruits-a-coque"],
    ingredients: ["60g de flocons d'avoine", "250ml de lait (ou végétal)", "Fruits rouges (frais ou surgelés)", "1 c. à soupe d'amandes effilées", "Miel ou sirop d'érable"],
    steps: [
      "Cuire les flocons d'avoine dans le lait 5 min à feu doux",
      "Verser dans un bol, ajouter les fruits rouges",
      "Parsemer d'amandes effilées et d'un trait de miel",
    ],
    tip: "Remplace le lait par du lait végétal et le miel par du sirop d'agave pour une version 100% vegan.",
  },
  {
    id: "pdj-pancakes-proteines",
    name: "Pancakes protéinés banane-avoine",
    meal: "petit-dej",
    diet: ["vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["moelleux"],
    price: 1,
    region: "France entière",
    prepMinutes: 15,
    kcal: 510,
    protein: 36,
    carbs: 62,
    fat: 12,
    allergens: ["oeuf", "lactose"],
    ingredients: ["1 banane mûre", "2 œufs", "40g de flocons d'avoine mixés", "30g de whey vanille", "1/2 c. à café de levure", "Un peu de lait"],
    steps: [
      "Mixer tous les ingrédients pour obtenir une pâte lisse",
      "Cuire des petites portions à la poêle chaude, 2 min par face",
      "Servir avec fruits frais ou un peu de beurre de cacahuète",
    ],
    tip: "Excellent petit-déj pré ou post-séance grâce au ratio glucides/protéines.",
  },
  {
    id: "pdj-bol-skyr-granola",
    name: "Bol de skyr, granola maison et fruits de saison",
    meal: "petit-dej",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux", "croquant"],
    price: 2,
    region: "France entière",
    prepMinutes: 5,
    kcal: 320,
    protein: 30,
    carbs: 32,
    fat: 8,
    allergens: ["lactose", "fruits-a-coque"],
    ingredients: ["200g de skyr nature", "30g de granola pauvre en sucre", "Fruits de saison (pomme, poire, fruits rouges)", "Cannelle"],
    steps: [
      "Verser le skyr dans un bol",
      "Ajouter les fruits coupés et le granola",
      "Saupoudrer de cannelle",
    ],
    tip: "Le skyr a deux fois plus de protéines qu'un yaourt grec classique pour le même nombre de calories — parfait en sèche.",
  },
  {
    id: "pdj-toast-avocat-oeuf",
    name: "Toast avocat, œuf poché et graines",
    meal: "petit-dej",
    diet: ["vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["croquant", "fondant"],
    price: 2,
    region: "France entière",
    prepMinutes: 12,
    kcal: 440,
    protein: 20,
    carbs: 32,
    fat: 26,
    allergens: ["gluten", "oeuf"],
    ingredients: ["2 tranches de pain complet", "1/2 avocat", "1 œuf", "Graines de sésame/courge", "Citron, piment d'Espelette"],
    steps: [
      "Toaster le pain",
      "Écraser l'avocat avec citron et sel, étaler sur le pain",
      "Pocher l'œuf 3 min dans l'eau frémissante avec un peu de vinaigre",
      "Déposer l'œuf sur le toast, parsemer de graines et de piment",
    ],
    tip: "Version sans gluten facile : pain de sarrasin ou de riz.",
  },
  {
    id: "pdj-smoothie-bowl-mangue",
    name: "Smoothie bowl mangue-passion",
    meal: "petit-dej",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete"],
    temp: "froid",
    texture: ["crémeux", "croquant"],
    price: 2,
    region: "France entière (fruits exotiques importés)",
    prepMinutes: 10,
    kcal: 290,
    protein: 8,
    carbs: 52,
    fat: 6,
    allergens: ["fruits-a-coque"],
    ingredients: ["1 mangue congelée", "1 banane", "100ml de lait végétal", "1 fruit de la passion", "Noix de coco râpée, granola"],
    steps: [
      "Mixer mangue, banane et lait végétal jusqu'à texture épaisse",
      "Verser dans un bol",
      "Garnir de fruit de la passion, coco râpée et granola",
    ],
    tip: "Très rafraîchissant après une séance d'été — facile à digérer avant un entraînement aussi.",
  },
  {
    id: "pdj-pain-perdu-proteine",
    name: "Pain perdu protéiné cannelle",
    meal: "petit-dej",
    diet: ["vegetarien"],
    phases: ["surplus"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["moelleux", "fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 12,
    kcal: 480,
    protein: 28,
    carbs: 58,
    fat: 14,
    allergens: ["gluten", "oeuf", "lactose"],
    ingredients: ["2-3 tranches de pain rassis", "2 œufs", "20g de whey vanille diluée dans du lait", "Cannelle", "Un peu de beurre pour la cuisson"],
    steps: [
      "Mélanger œufs, lait protéiné et cannelle",
      "Tremper les tranches de pain 30 sec de chaque côté",
      "Cuire à la poêle beurrée 2-3 min par face",
      "Servir avec fruits ou sirop d'érable",
    ],
    tip: "Pain rassis = idéal, il absorbe mieux le mélange sans se déliter.",
  },

  // ─────────────────────────── DÉJEUNER ───────────────────────────
  {
    id: "dej-poulet-riz-brocoli",
    name: "Poulet grillé, riz basmati et brocoli vapeur",
    meal: "dejeuner",
    diet: ["omnivore"],
    phases: ["surplus", "maintenance", "deficit"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["moelleux", "croquant"],
    price: 2,
    region: "France entière",
    prepMinutes: 25,
    kcal: 520,
    protein: 48,
    carbs: 55,
    fat: 10,
    allergens: [],
    ingredients: ["180g de blanc de poulet", "80g de riz basmati (cru)", "200g de brocoli", "Huile d'olive, ail, paprika"],
    steps: [
      "Mariner le poulet avec ail, paprika et huile d'olive",
      "Cuire le riz selon les instructions",
      "Griller le poulet 6-7 min par face",
      "Cuire le brocoli à la vapeur 6 min, assaisonner",
    ],
    tip: "Le plat de référence en musculation — ajuste juste la quantité de riz selon ta phase.",
  },
  {
    id: "dej-buddha-bowl-pois-chiches",
    name: "Buddha bowl pois chiches rôtis et tahini",
    meal: "dejeuner",
    diet: ["vegan", "vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["toute-saison"],
    temp: "tiede",
    texture: ["croquant", "crémeux"],
    price: 2,
    region: "France entière (inspiration méditerranéenne)",
    prepMinutes: 30,
    kcal: 470,
    protein: 20,
    carbs: 58,
    fat: 18,
    allergens: ["soja"],
    ingredients: ["200g de pois chiches cuits", "Quinoa", "Carottes, chou rouge, concombre", "Sauce tahini-citron", "Graines de sésame"],
    steps: [
      "Rôtir les pois chiches au four 20 min avec cumin et paprika",
      "Cuire le quinoa",
      "Disposer tous les légumes crus et le quinoa dans un bol",
      "Arroser de sauce tahini-citron",
    ],
    tip: "Excellente source de protéines végétales complètes en combinant légumineuse + céréale.",
  },
  {
    id: "dej-saumon-patate-douce",
    name: "Pavé de saumon, purée de patate douce, épinards",
    meal: "dejeuner",
    diet: ["pescetarien", "omnivore"],
    phases: ["surplus", "maintenance"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["fondant", "crémeux"],
    price: 3,
    region: "Bretagne / Norvège (saumon)",
    prepMinutes: 25,
    kcal: 580,
    protein: 38,
    carbs: 48,
    fat: 24,
    allergens: ["poisson"],
    ingredients: ["150g de pavé de saumon", "250g de patate douce", "Épinards frais", "Huile d'olive, citron, aneth"],
    steps: [
      "Cuire la patate douce à l'eau, écraser en purée avec un peu d'huile d'olive",
      "Cuire le saumon à la poêle peau croustillante, 4 min par face",
      "Faire revenir les épinards 2 min",
      "Dresser et arroser de citron",
    ],
    tip: "Riche en oméga-3 — excellent pour la récupération articulaire des sportifs.",
  },
  {
    id: "dej-salade-lentilles-feta",
    name: "Salade de lentilles, feta et tomates confites",
    meal: "dejeuner",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete", "printemps"],
    temp: "froid",
    texture: ["fondant", "croquant"],
    price: 2,
    region: "Provence",
    prepMinutes: 20,
    kcal: 420,
    protein: 22,
    carbs: 40,
    fat: 18,
    allergens: ["lactose"],
    ingredients: ["200g de lentilles corail ou vertes cuites", "60g de feta", "Tomates cerises confites", "Roquette, huile d'olive, vinaigre balsamique"],
    steps: [
      "Mélanger les lentilles tiédies avec huile d'olive et vinaigre",
      "Ajouter la roquette et les tomates confites",
      "Émietter la feta sur le dessus",
    ],
    tip: "Parfaite en lunchbox, se prépare la veille et se mange froide ou tiède.",
  },
  {
    id: "dej-wrap-dinde-crudites",
    name: "Wrap de dinde, crudités et sauce yaourt",
    meal: "dejeuner",
    diet: ["omnivore"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["croquant"],
    price: 1,
    region: "France entière",
    prepMinutes: 10,
    kcal: 380,
    protein: 32,
    carbs: 38,
    fat: 10,
    allergens: ["gluten", "lactose"],
    ingredients: ["1 galette de blé complet", "120g de blanc de dinde", "Carotte, concombre, salade", "Yaourt grec, moutarde, citron"],
    steps: [
      "Mélanger yaourt, moutarde et citron pour la sauce",
      "Garnir la galette de crudités et de dinde",
      "Napper de sauce, rouler serré",
    ],
    tip: "Idéal pour un repas rapide au bureau — se prépare en moins de 10 minutes.",
  },
  {
    id: "dej-pates-completes-thon",
    name: "Pâtes complètes, thon, olives et tomates",
    meal: "dejeuner",
    diet: ["pescetarien"],
    phases: ["surplus", "maintenance"],
    season: ["ete"],
    temp: "tiede",
    texture: ["fondant"],
    price: 1,
    region: "Méditerranée / Sud de la France",
    prepMinutes: 18,
    kcal: 540,
    protein: 36,
    carbs: 65,
    fat: 14,
    allergens: ["gluten", "poisson"],
    ingredients: ["90g de pâtes complètes (crues)", "1 boîte de thon au naturel", "Tomates cerises, olives noires", "Huile d'olive, basilic, ail"],
    steps: [
      "Cuire les pâtes al dente",
      "Faire revenir l'ail et les tomates 5 min",
      "Ajouter le thon égoutté et les olives",
      "Mélanger avec les pâtes, basilic frais",
    ],
    tip: "Version sans gluten : utilise des pâtes de lentilles ou de riz.",
  },
  {
    id: "dej-curry-pois-chiches-vegan",
    name: "Curry de pois chiches et lait de coco",
    meal: "dejeuner",
    diet: ["vegan", "vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["crémeux"],
    price: 1,
    region: "France entière (inspiration indienne)",
    prepMinutes: 25,
    kcal: 480,
    protein: 16,
    carbs: 52,
    fat: 22,
    allergens: [],
    ingredients: ["240g de pois chiches cuits", "200ml de lait de coco", "Oignon, ail, gingembre", "Curry, curcuma, cumin", "Riz basmati"],
    steps: [
      "Faire revenir oignon, ail et gingembre",
      "Ajouter les épices puis le lait de coco",
      "Incorporer les pois chiches, mijoter 15 min",
      "Servir sur riz basmati",
    ],
    tip: "Se congèle très bien — fais une double dose pour la semaine.",
  },
  {
    id: "dej-steak-haricots-verts",
    name: "Steak de bœuf, haricots verts et riz",
    meal: "dejeuner",
    diet: ["omnivore"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant", "croquant"],
    price: 3,
    region: "Charolais / France entière",
    prepMinutes: 20,
    kcal: 560,
    protein: 45,
    carbs: 45,
    fat: 20,
    allergens: [],
    ingredients: ["180g de steak de bœuf", "200g de haricots verts", "70g de riz (cru)", "Beurre, ail, thym"],
    steps: [
      "Cuire le riz",
      "Cuire les haricots verts à la vapeur 8 min",
      "Saisir le steak 2-3 min par face avec beurre, ail et thym",
      "Laisser reposer 3 min avant de trancher",
    ],
    tip: "Pour la sèche, réduis simplement la portion de riz à 50g.",
  },
  {
    id: "dej-tofu-saute-legumes",
    name: "Tofu sauté, légumes croquants et sauce soja-gingembre",
    meal: "dejeuner",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["croquant", "fondant"],
    price: 1,
    region: "France entière (inspiration asiatique)",
    prepMinutes: 18,
    kcal: 380,
    protein: 24,
    carbs: 30,
    fat: 18,
    allergens: ["soja"],
    ingredients: ["200g de tofu ferme", "Poivrons, brocoli, carottes", "Sauce soja, gingembre, ail", "Huile de sésame"],
    steps: [
      "Presser et couper le tofu en dés, le saisir à la poêle jusqu'à coloration",
      "Réserver, faire sauter les légumes 5 min à feu vif",
      "Réunir tofu et légumes, ajouter sauce soja, gingembre et ail",
      "Finir avec un trait d'huile de sésame",
    ],
    tip: "Presser le tofu au moins 15 min avant cuisson pour une texture bien croustillante.",
  },
  {
    id: "dej-quiche-legere-courgette",
    name: "Quiche sans pâte courgette-chèvre",
    meal: "dejeuner",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete"],
    temp: "tiede",
    texture: ["fondant", "moelleux"],
    price: 2,
    region: "Provence",
    prepMinutes: 35,
    kcal: 350,
    protein: 24,
    carbs: 12,
    fat: 22,
    allergens: ["oeuf", "lactose"],
    ingredients: ["4 œufs", "200ml de lait", "1 courgette", "80g de chèvre frais", "Herbes de Provence"],
    steps: [
      "Couper la courgette en fines rondelles, les faire suer 5 min",
      "Battre œufs et lait, assaisonner",
      "Verser dans un plat avec la courgette et le chèvre émietté",
      "Cuire 25 min à 180°C",
    ],
    tip: "Sans pâte = beaucoup moins de glucides et de calories qu'une quiche classique, idéal en sèche.",
  },

  // ─────────────────────────── DÎNER ───────────────────────────
  {
    id: "din-cabillaud-legumes-four",
    name: "Cabillaud en papillote et légumes rôtis",
    meal: "diner",
    diet: ["pescetarien"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant"],
    price: 2,
    region: "Atlantique / France entière",
    prepMinutes: 30,
    kcal: 380,
    protein: 38,
    carbs: 22,
    fat: 14,
    allergens: ["poisson"],
    ingredients: ["180g de cabillaud", "Courgette, poivron, tomate", "Citron, thym, huile d'olive"],
    steps: [
      "Disposer le poisson et les légumes coupés sur du papier sulfurisé",
      "Arroser d'huile d'olive, citron et thym",
      "Fermer la papillote, cuire 20 min à 200°C",
    ],
    tip: "Plat très léger en calories mais rassasiant — parfait pour un dîner en phase de sèche.",
  },
  {
    id: "din-soupe-legumes-hiver",
    name: "Velouté de légumes d'hiver et croûtons",
    meal: "diner",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit"],
    season: ["hiver", "automne"],
    temp: "chaud",
    texture: ["crémeux", "croquant"],
    price: 1,
    region: "France entière",
    prepMinutes: 30,
    kcal: 220,
    protein: 6,
    carbs: 32,
    fat: 6,
    allergens: ["gluten"],
    ingredients: ["Carottes, potiron, poireaux", "Bouillon de légumes", "Pain grillé en croûtons", "Crème végétale (optionnel)"],
    steps: [
      "Faire revenir les légumes coupés 5 min",
      "Ajouter le bouillon, cuire 25 min",
      "Mixer jusqu'à texture lisse",
      "Servir avec croûtons et un trait de crème végétale",
    ],
    tip: "Très faible en calories pour le volume — excellent dîner en déficit qui cale bien.",
  },
  {
    id: "din-omelette-jambon-salade",
    name: "Omelette jambon blanc et salade verte",
    meal: "diner",
    diet: ["omnivore"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 10,
    kcal: 340,
    protein: 30,
    carbs: 4,
    fat: 22,
    allergens: ["oeuf"],
    ingredients: ["3 œufs", "1 tranche de jambon blanc", "Salade verte", "Vinaigrette légère"],
    steps: [
      "Battre les œufs, ajouter le jambon coupé en dés",
      "Cuire à la poêle 3-4 min",
      "Servir avec une salade verte assaisonnée",
    ],
    tip: "Le dîner classique 'sans prise de tête' pour rester dans ses macros sans calculer.",
  },
  {
    id: "din-poke-bowl-saumon",
    name: "Poke bowl saumon, riz vinaigré et edamame",
    meal: "diner",
    diet: ["pescetarien"],
    phases: ["maintenance", "surplus"],
    season: ["ete"],
    temp: "froid",
    texture: ["fondant", "croquant"],
    price: 3,
    region: "France entière (inspiration hawaïenne)",
    prepMinutes: 20,
    kcal: 520,
    protein: 34,
    carbs: 55,
    fat: 16,
    allergens: ["poisson", "soja"],
    ingredients: ["150g de saumon frais (qualité sashimi)", "Riz vinaigré", "Edamame, avocat, concombre", "Sauce soja, sésame"],
    steps: [
      "Cuire le riz, l'assaisonner avec vinaigre de riz et sucre",
      "Couper le saumon en cubes",
      "Disposer riz, saumon, edamame, avocat et concombre dans un bol",
      "Arroser de sauce soja et graines de sésame",
    ],
    tip: "Achète un saumon labellisé 'qualité sashimi' chez le poissonnier si tu le manges cru.",
  },
  {
    id: "din-ratatouille-oeuf",
    name: "Ratatouille provençale et œuf au plat",
    meal: "diner",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete"],
    temp: "chaud",
    texture: ["fondant"],
    price: 1,
    region: "Provence",
    prepMinutes: 35,
    kcal: 320,
    protein: 16,
    carbs: 22,
    fat: 18,
    allergens: ["oeuf"],
    ingredients: ["Courgette, aubergine, poivron, tomate", "Ail, oignon, herbes de Provence", "2 œufs", "Huile d'olive"],
    steps: [
      "Couper tous les légumes en dés",
      "Faire mijoter 30 min avec ail, oignon et herbes",
      "Cuire les œufs au plat",
      "Servir la ratatouille surmontée des œufs",
    ],
    tip: "Recette estivale typique du sud de la France, se prépare en grande quantité et se réchauffe toute la semaine.",
  },
  {
    id: "din-galette-sarrasin-jambon",
    name: "Galette de sarrasin jambon-œuf-fromage (complète bretonne)",
    meal: "diner",
    diet: ["omnivore"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant", "croquant"],
    price: 2,
    region: "Bretagne",
    prepMinutes: 20,
    kcal: 480,
    protein: 32,
    carbs: 38,
    fat: 22,
    allergens: ["oeuf", "lactose"],
    ingredients: ["1 galette de sarrasin", "1 tranche de jambon", "1 œuf", "Emmental râpé"],
    steps: [
      "Chauffer la galette dans une poêle",
      "Casser l'œuf au centre, ajouter jambon et fromage",
      "Replier les bords en carré, cuire jusqu'à ce que le blanc soit pris",
    ],
    tip: "Le sarrasin est naturellement sans gluten — vérifie juste que la galette est pure sarrasin si allergie.",
  },
  {
    id: "din-dahl-lentilles-corail",
    name: "Dahl de lentilles corail au lait de coco",
    meal: "diner",
    diet: ["vegan", "vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["crémeux"],
    price: 1,
    region: "France entière (inspiration indienne)",
    prepMinutes: 30,
    kcal: 400,
    protein: 18,
    carbs: 48,
    fat: 14,
    allergens: [],
    ingredients: ["200g de lentilles corail", "150ml de lait de coco", "Curcuma, cumin, coriandre", "Oignon, ail, tomate"],
    steps: [
      "Faire revenir oignon et ail, ajouter les épices",
      "Ajouter lentilles, tomate et eau, cuire 20 min",
      "Incorporer le lait de coco en fin de cuisson",
      "Servir avec coriandre fraîche",
    ],
    tip: "Plat réconfortant et économique, riche en fibres pour la satiété en phase de sèche.",
  },
  {
    id: "din-tartare-boeuf-frites-patate",
    name: "Tartare de bœuf maison et frites de patate douce au four",
    meal: "diner",
    diet: ["omnivore"],
    phases: ["surplus"],
    season: ["toute-saison"],
    temp: "tiede",
    texture: ["fondant", "croquant"],
    price: 3,
    region: "France entière",
    prepMinutes: 25,
    kcal: 560,
    protein: 38,
    carbs: 42,
    fat: 26,
    allergens: ["oeuf"],
    ingredients: ["180g de filet de bœuf haché au couteau", "1 jaune d'œuf", "Échalote, câpres, moutarde, Worcestershire", "Patate douce en frites au four"],
    steps: [
      "Couper la patate douce en bâtonnets, cuire au four 25 min à 200°C",
      "Hacher la viande au couteau finement",
      "Mélanger avec échalote, câpres, moutarde et jaune d'œuf",
      "Servir avec les frites de patate douce",
    ],
    tip: "Utilise une viande très fraîche achetée le jour même chez un bon boucher.",
  },
  {
    id: "din-couscous-legumes-pois-chiches",
    name: "Couscous de légumes et pois chiches",
    meal: "diner",
    diet: ["vegan", "vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["automne", "hiver"],
    temp: "chaud",
    texture: ["moelleux"],
    price: 1,
    region: "France entière (inspiration maghrébine)",
    prepMinutes: 35,
    kcal: 460,
    protein: 16,
    carbs: 70,
    fat: 12,
    allergens: ["gluten"],
    ingredients: ["Semoule de couscous", "Carotte, navet, courgette, pois chiches", "Bouillon, ras el hanout, raisins secs"],
    steps: [
      "Cuire les légumes et pois chiches dans le bouillon épicé 25 min",
      "Préparer la semoule selon les instructions",
      "Servir les légumes sur la semoule, arroser de bouillon",
    ],
    tip: "Pour version sans gluten, remplace la semoule par du riz ou du quinoa.",
  },
  {
    id: "din-blanquette-legere-dinde",
    name: "Blanquette de dinde allégée et riz",
    meal: "diner",
    diet: ["omnivore"],
    phases: ["maintenance", "surplus"],
    season: ["hiver"],
    temp: "chaud",
    texture: ["fondant", "crémeux"],
    price: 2,
    region: "France entière (classique français)",
    prepMinutes: 40,
    kcal: 480,
    protein: 40,
    carbs: 45,
    fat: 14,
    allergens: ["lactose"],
    ingredients: ["200g de dinde en cubes", "Carotte, champignons, oignon", "Crème légère, bouillon", "Riz basmati"],
    steps: [
      "Faire revenir la dinde, ajouter oignon et carotte",
      "Couvrir de bouillon, mijoter 25 min",
      "Ajouter champignons et crème légère en fin de cuisson",
      "Servir avec du riz",
    ],
    tip: "Version 'fitness' du classique français — remplace la crème entière par de la crème à 4% MG.",
  },

  // ─────────────────────────── COLLATIONS ───────────────────────────
  {
    id: "col-fromage-blanc-miel",
    name: "Fromage blanc, miel et noix",
    meal: "collation",
    diet: ["vegetarien"],
    phases: ["maintenance", "deficit"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux", "croquant"],
    price: 1,
    region: "France entière",
    prepMinutes: 3,
    kcal: 220,
    protein: 18,
    carbs: 16,
    fat: 9,
    allergens: ["lactose", "fruits-a-coque"],
    ingredients: ["200g de fromage blanc 20%", "1 c. à café de miel", "Quelques noix concassées"],
    steps: ["Mélanger le fromage blanc et le miel", "Ajouter les noix concassées"],
    tip: "Collation express très riche en caséine, idéale en soirée pour la récupération nocturne.",
  },
  {
    id: "col-pomme-beurre-cacahuete",
    name: "Pomme et beurre de cacahuète",
    meal: "collation",
    diet: ["vegan", "vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["automne"],
    temp: "froid",
    texture: ["croquant", "crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 2,
    kcal: 280,
    protein: 8,
    carbs: 30,
    fat: 16,
    allergens: ["arachide"],
    ingredients: ["1 pomme", "1,5 c. à soupe de beurre de cacahuète 100%"],
    steps: ["Couper la pomme en tranches", "Tremper dans le beurre de cacahuète"],
    tip: "Choisis un beurre de cacahuète sans sucre ajouté (liste d'ingrédients = juste 'cacahuètes').",
  },
  {
    id: "col-houmous-batonnets",
    name: "Houmous et bâtonnets de légumes",
    meal: "collation",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux", "croquant"],
    price: 1,
    region: "France entière (inspiration moyen-orientale)",
    prepMinutes: 10,
    kcal: 180,
    protein: 7,
    carbs: 18,
    fat: 9,
    allergens: [],
    ingredients: ["100g de houmous maison ou du commerce", "Carotte, concombre, céleri en bâtonnets"],
    steps: ["Couper les légumes en bâtonnets", "Servir avec le houmous"],
    tip: "Très peu calorique pour le volume — combat bien les fringales en phase de sèche.",
  },
  {
    id: "col-shaker-whey-banane",
    name: "Shaker whey-banane-lait",
    meal: "collation",
    diet: ["vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 3,
    kcal: 320,
    protein: 32,
    carbs: 35,
    fat: 5,
    allergens: ["lactose"],
    ingredients: ["30g de whey", "1 banane", "250ml de lait demi-écrémé"],
    steps: ["Mixer tous les ingrédients", "Servir immédiatement bien frais"],
    tip: "Pratique quand l'appétit manque en surplus calorique — facile à boire même sans faim.",
  },
  {
    id: "col-oeufs-durs-paprika",
    name: "Œufs durs au paprika",
    meal: "collation",
    diet: ["omnivore", "vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 10,
    kcal: 150,
    protein: 13,
    carbs: 1,
    fat: 10,
    allergens: ["oeuf"],
    ingredients: ["2 œufs", "Paprika, sel"],
    steps: ["Cuire les œufs 9-10 min à l'eau bouillante", "Écaler, saupoudrer de paprika et sel"],
    tip: "Se prépare en lot pour 4-5 jours — collation la moins chère du marché en protéines.",
  },
  {
    id: "col-barres-dattes-cacao",
    name: "Barres maison datte-amande-cacao",
    meal: "collation",
    diet: ["vegan", "vegetarien"],
    phases: ["surplus"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["fondant", "croquant"],
    price: 2,
    region: "France entière",
    prepMinutes: 15,
    kcal: 240,
    protein: 6,
    carbs: 28,
    fat: 12,
    allergens: ["fruits-a-coque"],
    ingredients: ["150g de dattes dénoyautées", "100g d'amandes", "2 c. à soupe de cacao non sucré", "Pincée de sel"],
    steps: [
      "Mixer dattes et amandes jusqu'à obtenir une pâte collante",
      "Ajouter le cacao, mixer à nouveau",
      "Étaler dans un moule, tasser et réfrigérer 1h",
      "Découper en barres",
    ],
    tip: "Se conserve 1 semaine au frigo dans une boîte hermétique — parfait pour le sac de sport.",
  },
  {
    id: "col-skyr-cacao-fruits-rouges",
    name: "Skyr cacao et fruits rouges",
    meal: "collation",
    diet: ["vegetarien"],
    phases: ["deficit"],
    season: ["ete"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 4,
    kcal: 160,
    protein: 22,
    carbs: 14,
    fat: 2,
    allergens: ["lactose"],
    ingredients: ["200g de skyr nature", "1 c. à café de cacao non sucré", "Fruits rouges"],
    steps: ["Mélanger le skyr et le cacao", "Ajouter les fruits rouges par-dessus"],
    tip: "Effet 'dessert' avec très peu de calories — excellent pour gérer les envies de sucré en sèche.",
  },
  {
    id: "col-toast-fromage-frais-radis",
    name: "Tartine fromage frais et radis",
    meal: "collation",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["printemps", "ete"],
    temp: "froid",
    texture: ["croquant", "crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 5,
    kcal: 190,
    protein: 10,
    carbs: 20,
    fat: 7,
    allergens: ["gluten", "lactose"],
    ingredients: ["1 tranche de pain complet", "30g de fromage frais (type Saint Môret light)", "Radis émincés", "Ciboulette"],
    steps: ["Tartiner le pain de fromage frais", "Disposer les radis émincés", "Parsemer de ciboulette"],
    tip: "Croquant et frais — parfaite collation de printemps quand les radis sont au top de leur saison.",
  },

  // ─────────────────────────── POST-TRAINING ───────────────────────────
  {
    id: "post-shaker-whey-flocons",
    name: "Shaker whey, flocons d'avoine et flocons de banane",
    meal: "post-training",
    diet: ["vegetarien"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 3,
    kcal: 380,
    protein: 34,
    carbs: 45,
    fat: 6,
    allergens: ["lactose"],
    ingredients: ["30g de whey", "40g de flocons d'avoine", "1 banane", "300ml d'eau ou lait"],
    steps: ["Mixer tous les ingrédients", "Boire dans les 30-45 min après l'entraînement"],
    tip: "Ratio glucides/protéines idéal pour relancer la synthèse de glycogène et protéique post-effort.",
  },
  {
    id: "post-riz-au-lait-proteine",
    name: "Riz au lait protéiné (façon récupération)",
    meal: "post-training",
    diet: ["vegetarien"],
    phases: ["surplus"],
    season: ["hiver"],
    temp: "chaud",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 25,
    kcal: 420,
    protein: 26,
    carbs: 60,
    fat: 8,
    allergens: ["lactose"],
    ingredients: ["60g de riz rond", "400ml de lait", "20g de whey vanille (hors du feu)", "Cannelle, vanille"],
    steps: [
      "Cuire le riz dans le lait à feu doux 20 min en remuant",
      "Hors du feu, incorporer la whey une fois tiède",
      "Saupoudrer de cannelle",
    ],
    tip: "N'ajoute jamais la whey à chaud (>60°C) pour éviter qu'elle ne coagule.",
  },
  {
    id: "post-poulet-patate-rapide",
    name: "Émincé de poulet et patate douce vapeur (récup express)",
    meal: "post-training",
    diet: ["omnivore"],
    phases: ["surplus", "maintenance"],
    season: ["toute-saison"],
    temp: "chaud",
    texture: ["fondant"],
    price: 2,
    region: "France entière",
    prepMinutes: 20,
    kcal: 450,
    protein: 42,
    carbs: 48,
    fat: 8,
    allergens: [],
    ingredients: ["180g de poulet émincé", "250g de patate douce", "Sel, épices au choix"],
    steps: [
      "Cuire la patate douce coupée en dés à la vapeur 15 min",
      "Saisir le poulet émincé 6-8 min à la poêle",
      "Assaisonner et servir",
    ],
    tip: "Repas simple et rapide à préparer dès le retour de la salle, sans sauce lourde à digérer.",
  },
  {
    id: "post-smoothie-fruits-proteine",
    name: "Smoothie protéiné fruits rouges et yaourt grec",
    meal: "post-training",
    diet: ["vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["ete"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 5,
    kcal: 260,
    protein: 28,
    carbs: 28,
    fat: 4,
    allergens: ["lactose"],
    ingredients: ["150g de yaourt grec 0%", "Fruits rouges surgelés", "1/2 banane", "Eau ou glaçons"],
    steps: ["Mixer tous les ingrédients jusqu'à texture lisse", "Boire frais"],
    tip: "Faible en calories mais riche en protéines — parfait quand tu es en sèche et que tu veux limiter l'apport calorique post-séance.",
  },
  {
    id: "post-galette-riz-jambon-fromage",
    name: "Galettes de riz, jambon et fromage (snack express)",
    meal: "post-training",
    diet: ["omnivore"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["croquant", "fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 5,
    kcal: 280,
    protein: 24,
    carbs: 30,
    fat: 7,
    allergens: ["lactose"],
    ingredients: ["3 galettes de riz soufflé", "2 tranches de jambon blanc", "Fromage type cottage ou tranche light"],
    steps: ["Garnir chaque galette de jambon et fromage", "Manger directement, sans cuisson"],
    tip: "Solution la plus rapide pour un apport rapide en protéines + glucides sans cuisine, parfait en sac de sport.",
  },
  {
    id: "post-tofu-soja-riz-rapide",
    name: "Tofu mariné soja, riz vinaigré rapide",
    meal: "post-training",
    diet: ["vegan", "vegetarien"],
    phases: ["maintenance", "surplus"],
    season: ["toute-saison"],
    temp: "tiede",
    texture: ["fondant"],
    price: 1,
    region: "France entière",
    prepMinutes: 15,
    kcal: 400,
    protein: 22,
    carbs: 52,
    fat: 10,
    allergens: ["soja"],
    ingredients: ["200g de tofu ferme", "Riz blanc précuit", "Sauce soja, gingembre", "Huile de sésame"],
    steps: [
      "Mariner le tofu coupé en dés dans la sauce soja et gingembre 5 min",
      "Saisir à la poêle 5 min",
      "Servir sur le riz chaud avec un filet d'huile de sésame",
    ],
    tip: "Le riz précuit en poche micro-ondable est un allié post-training quand le temps manque.",
  },

  // ─────────────────────────── DESSERTS SAINS ───────────────────────────
  {
    id: "des-mousse-chocolat-avocat",
    name: "Mousse au chocolat avocat-cacao (sans sucre ajouté)",
    meal: "dessert",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit", "maintenance"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["crémeux"],
    price: 2,
    region: "France entière",
    prepMinutes: 10,
    kcal: 240,
    protein: 4,
    carbs: 18,
    fat: 18,
    allergens: [],
    ingredients: ["1 avocat mûr", "3 c. à soupe de cacao non sucré", "2 c. à soupe de sirop d'érable", "Lait végétal si besoin"],
    steps: [
      "Mixer tous les ingrédients jusqu'à texture lisse et mousseuse",
      "Réfrigérer 30 min avant de servir",
    ],
    tip: "Le goût d'avocat disparaît complètement derrière le cacao — bluffant en texture.",
  },
  {
    id: "des-cookies-proteines-avoine",
    name: "Cookies protéinés avoine et pépites de chocolat",
    meal: "dessert",
    diet: ["vegetarien"],
    phases: ["surplus"],
    season: ["toute-saison"],
    temp: "froid",
    texture: ["moelleux", "croquant"],
    price: 1,
    region: "France entière",
    prepMinutes: 25,
    kcal: 180,
    protein: 10,
    carbs: 20,
    fat: 7,
    allergens: ["gluten", "oeuf"],
    ingredients: ["100g de flocons d'avoine mixés", "30g de whey chocolat", "1 œuf", "1 banane écrasée", "Pépites de chocolat noir"],
    steps: [
      "Mélanger tous les ingrédients secs puis humides",
      "Façonner des petits tas sur plaque",
      "Cuire 12 min à 180°C",
    ],
    tip: "Idéal en collation post-training si tu es en surplus calorique — calorique mais riche en protéines.",
  },
  {
    id: "des-compote-pomme-cannelle",
    name: "Compote pomme-cannelle maison (sans sucre ajouté)",
    meal: "dessert",
    diet: ["vegan", "vegetarien"],
    phases: ["deficit"],
    season: ["automne"],
    temp: "tiede",
    texture: ["fondant"],
    price: 1,
    region: "Normandie",
    prepMinutes: 20,
    kcal: 90,
    protein: 0,
    carbs: 22,
    fat: 0,
    allergens: [],
    ingredients: ["4 pommes", "Cannelle", "Un peu d'eau"],
    steps: [
      "Couper les pommes en dés",
      "Cuire à feu doux avec un fond d'eau et cannelle 15 min",
      "Mixer ou écraser grossièrement selon la texture désirée",
    ],
    tip: "Les pommes normandes (Reinette, Golden) donnent naturellement une compote bien sucrée sans rien ajouter.",
  },
  {
    id: "des-yaourt-glace-fruits",
    name: "Yaourt glacé maison aux fruits (sorbet minute)",
    meal: "dessert",
    diet: ["vegetarien"],
    phases: ["deficit"],
    season: ["ete"],
    temp: "froid",
    texture: ["crémeux"],
    price: 1,
    region: "France entière",
    prepMinutes: 5,
    kcal: 130,
    protein: 12,
    carbs: 16,
    fat: 2,
    allergens: ["lactose"],
    ingredients: ["200g de yaourt grec 0%", "150g de fruits congelés (mangue, fruits rouges)", "1 c. à café de miel"],
    steps: ["Mixer tous les ingrédients jusqu'à consistance de glace", "Servir immédiatement"],
    tip: "Les fruits doivent être congelés pour obtenir la texture glacée sans sorbetière.",
  },
  {
    id: "des-tarte-fine-figues",
    name: "Tarte fine aux figues et miel (pâte fine, peu de sucre)",
    meal: "dessert",
    diet: ["vegetarien"],
    phases: ["surplus"],
    season: ["ete", "automne"],
    temp: "tiede",
    texture: ["croquant", "fondant"],
    price: 2,
    region: "Sud-Ouest / Provence",
    prepMinutes: 30,
    kcal: 260,
    protein: 4,
    carbs: 38,
    fat: 9,
    allergens: ["gluten"],
    ingredients: ["1 pâte feuilletée fine", "6 figues fraîches", "1 c. à soupe de miel", "Romarin (optionnel)"],
    steps: [
      "Étaler la pâte, piquer à la fourchette",
      "Disposer les figues coupées en deux",
      "Napper de miel, cuire 20 min à 200°C",
    ],
    tip: "Les figues du Sud-Ouest et de Provence sont à leur meilleur fin août-septembre.",
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────

export function macroBadge(r: Recipe): string {
  return `${r.kcal} kcal · P ${r.protein}g · G ${r.carbs}g · L ${r.fat}g`;
}
